
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Roles = {
  admin: 'admin',
  editor: 'editor',
  coach: 'coach',
  organizer: 'organizer'
} as const

export type Roles = (typeof Roles)[keyof typeof Roles]
