
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Category` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Category
 * 
 */
export type CategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$CategoryPayload>

export type AggregateCategory = {
  _count: CategoryCountAggregateOutputType | null
  _min: CategoryMinAggregateOutputType | null
  _max: CategoryMaxAggregateOutputType | null
}

export type CategoryMinAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  age: string | null
  weight: string | null
}

export type CategoryMaxAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  age: string | null
  weight: string | null
}

export type CategoryCountAggregateOutputType = {
  id: number
  tournamentId: number
  age: number
  weight: number
  _all: number
}


export type CategoryMinAggregateInputType = {
  id?: true
  tournamentId?: true
  age?: true
  weight?: true
}

export type CategoryMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  age?: true
  weight?: true
}

export type CategoryCountAggregateInputType = {
  id?: true
  tournamentId?: true
  age?: true
  weight?: true
  _all?: true
}

export type CategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Category to aggregate.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Categories
  **/
  _count?: true | CategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CategoryMaxAggregateInputType
}

export type GetCategoryAggregateType<T extends CategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateCategory[P]>
}




export type CategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CategoryWhereInput
  orderBy?: Prisma.CategoryOrderByWithAggregationInput | Prisma.CategoryOrderByWithAggregationInput[]
  by: Prisma.CategoryScalarFieldEnum[] | Prisma.CategoryScalarFieldEnum
  having?: Prisma.CategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CategoryCountAggregateInputType | true
  _min?: CategoryMinAggregateInputType
  _max?: CategoryMaxAggregateInputType
}

export type CategoryGroupByOutputType = {
  id: string
  tournamentId: string | null
  age: string
  weight: string
  _count: CategoryCountAggregateOutputType | null
  _min: CategoryMinAggregateOutputType | null
  _max: CategoryMaxAggregateOutputType | null
}

export type GetCategoryGroupByPayload<T extends CategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CategoryGroupByOutputType[P]>
      }
    >
  >



export type CategoryWhereInput = {
  AND?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  OR?: Prisma.CategoryWhereInput[]
  NOT?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  id?: Prisma.StringFilter<"Category"> | string
  tournamentId?: Prisma.StringNullableFilter<"Category"> | string | null
  age?: Prisma.StringFilter<"Category"> | string
  weight?: Prisma.StringFilter<"Category"> | string
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  fighters?: Prisma.FighterListRelationFilter
  matches?: Prisma.MatchListRelationFilter
}

export type CategoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  tournament?: Prisma.TournamentOrderByWithRelationInput
  fighters?: Prisma.FighterOrderByRelationAggregateInput
  matches?: Prisma.MatchOrderByRelationAggregateInput
}

export type CategoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  OR?: Prisma.CategoryWhereInput[]
  NOT?: Prisma.CategoryWhereInput | Prisma.CategoryWhereInput[]
  tournamentId?: Prisma.StringNullableFilter<"Category"> | string | null
  age?: Prisma.StringFilter<"Category"> | string
  weight?: Prisma.StringFilter<"Category"> | string
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  fighters?: Prisma.FighterListRelationFilter
  matches?: Prisma.MatchListRelationFilter
}, "id">

export type CategoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  _count?: Prisma.CategoryCountOrderByAggregateInput
  _max?: Prisma.CategoryMaxOrderByAggregateInput
  _min?: Prisma.CategoryMinOrderByAggregateInput
}

export type CategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.CategoryScalarWhereWithAggregatesInput | Prisma.CategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.CategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CategoryScalarWhereWithAggregatesInput | Prisma.CategoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Category"> | string
  tournamentId?: Prisma.StringNullableWithAggregatesFilter<"Category"> | string | null
  age?: Prisma.StringWithAggregatesFilter<"Category"> | string
  weight?: Prisma.StringWithAggregatesFilter<"Category"> | string
}

export type CategoryCreateInput = {
  id?: string
  age: string
  weight: string
  tournament?: Prisma.TournamentCreateNestedOneWithoutCategoriesInput
  fighters?: Prisma.FighterCreateNestedManyWithoutCategoryInput
  matches?: Prisma.MatchCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateInput = {
  id?: string
  tournamentId?: string | null
  age: string
  weight: string
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutCategoryInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  tournament?: Prisma.TournamentUpdateOneWithoutCategoriesNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutCategoryNestedInput
  matches?: Prisma.MatchUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutCategoryNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateManyInput = {
  id?: string
  tournamentId?: string | null
  age: string
  weight: string
}

export type CategoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CategoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CategoryListRelationFilter = {
  every?: Prisma.CategoryWhereInput
  some?: Prisma.CategoryWhereInput
  none?: Prisma.CategoryWhereInput
}

export type CategoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CategoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type CategoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type CategoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  age?: Prisma.SortOrder
  weight?: Prisma.SortOrder
}

export type CategoryNullableScalarRelationFilter = {
  is?: Prisma.CategoryWhereInput | null
  isNot?: Prisma.CategoryWhereInput | null
}

export type CategoryCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutTournamentInput, Prisma.CategoryUncheckedCreateWithoutTournamentInput> | Prisma.CategoryCreateWithoutTournamentInput[] | Prisma.CategoryUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutTournamentInput | Prisma.CategoryCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.CategoryCreateManyTournamentInputEnvelope
  connect?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
}

export type CategoryUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutTournamentInput, Prisma.CategoryUncheckedCreateWithoutTournamentInput> | Prisma.CategoryCreateWithoutTournamentInput[] | Prisma.CategoryUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutTournamentInput | Prisma.CategoryCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.CategoryCreateManyTournamentInputEnvelope
  connect?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
}

export type CategoryUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutTournamentInput, Prisma.CategoryUncheckedCreateWithoutTournamentInput> | Prisma.CategoryCreateWithoutTournamentInput[] | Prisma.CategoryUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutTournamentInput | Prisma.CategoryCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.CategoryUpsertWithWhereUniqueWithoutTournamentInput | Prisma.CategoryUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.CategoryCreateManyTournamentInputEnvelope
  set?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  disconnect?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  delete?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  connect?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  update?: Prisma.CategoryUpdateWithWhereUniqueWithoutTournamentInput | Prisma.CategoryUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.CategoryUpdateManyWithWhereWithoutTournamentInput | Prisma.CategoryUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.CategoryScalarWhereInput | Prisma.CategoryScalarWhereInput[]
}

export type CategoryUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutTournamentInput, Prisma.CategoryUncheckedCreateWithoutTournamentInput> | Prisma.CategoryCreateWithoutTournamentInput[] | Prisma.CategoryUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutTournamentInput | Prisma.CategoryCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.CategoryUpsertWithWhereUniqueWithoutTournamentInput | Prisma.CategoryUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.CategoryCreateManyTournamentInputEnvelope
  set?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  disconnect?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  delete?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  connect?: Prisma.CategoryWhereUniqueInput | Prisma.CategoryWhereUniqueInput[]
  update?: Prisma.CategoryUpdateWithWhereUniqueWithoutTournamentInput | Prisma.CategoryUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.CategoryUpdateManyWithWhereWithoutTournamentInput | Prisma.CategoryUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.CategoryScalarWhereInput | Prisma.CategoryScalarWhereInput[]
}

export type CategoryCreateNestedOneWithoutMatchesInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutMatchesInput, Prisma.CategoryUncheckedCreateWithoutMatchesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutMatchesInput
  connect?: Prisma.CategoryWhereUniqueInput
}

export type CategoryUpdateOneWithoutMatchesNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutMatchesInput, Prisma.CategoryUncheckedCreateWithoutMatchesInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutMatchesInput
  upsert?: Prisma.CategoryUpsertWithoutMatchesInput
  disconnect?: Prisma.CategoryWhereInput | boolean
  delete?: Prisma.CategoryWhereInput | boolean
  connect?: Prisma.CategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CategoryUpdateToOneWithWhereWithoutMatchesInput, Prisma.CategoryUpdateWithoutMatchesInput>, Prisma.CategoryUncheckedUpdateWithoutMatchesInput>
}

export type CategoryCreateNestedOneWithoutFightersInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutFightersInput, Prisma.CategoryUncheckedCreateWithoutFightersInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutFightersInput
  connect?: Prisma.CategoryWhereUniqueInput
}

export type CategoryUpdateOneWithoutFightersNestedInput = {
  create?: Prisma.XOR<Prisma.CategoryCreateWithoutFightersInput, Prisma.CategoryUncheckedCreateWithoutFightersInput>
  connectOrCreate?: Prisma.CategoryCreateOrConnectWithoutFightersInput
  upsert?: Prisma.CategoryUpsertWithoutFightersInput
  disconnect?: Prisma.CategoryWhereInput | boolean
  delete?: Prisma.CategoryWhereInput | boolean
  connect?: Prisma.CategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CategoryUpdateToOneWithWhereWithoutFightersInput, Prisma.CategoryUpdateWithoutFightersInput>, Prisma.CategoryUncheckedUpdateWithoutFightersInput>
}

export type CategoryCreateWithoutTournamentInput = {
  id?: string
  age: string
  weight: string
  fighters?: Prisma.FighterCreateNestedManyWithoutCategoryInput
  matches?: Prisma.MatchCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutTournamentInput = {
  id?: string
  age: string
  weight: string
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutCategoryInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutTournamentInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutTournamentInput, Prisma.CategoryUncheckedCreateWithoutTournamentInput>
}

export type CategoryCreateManyTournamentInputEnvelope = {
  data: Prisma.CategoryCreateManyTournamentInput | Prisma.CategoryCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type CategoryUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.CategoryWhereUniqueInput
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutTournamentInput, Prisma.CategoryUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutTournamentInput, Prisma.CategoryUncheckedCreateWithoutTournamentInput>
}

export type CategoryUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.CategoryWhereUniqueInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutTournamentInput, Prisma.CategoryUncheckedUpdateWithoutTournamentInput>
}

export type CategoryUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.CategoryScalarWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateManyMutationInput, Prisma.CategoryUncheckedUpdateManyWithoutTournamentInput>
}

export type CategoryScalarWhereInput = {
  AND?: Prisma.CategoryScalarWhereInput | Prisma.CategoryScalarWhereInput[]
  OR?: Prisma.CategoryScalarWhereInput[]
  NOT?: Prisma.CategoryScalarWhereInput | Prisma.CategoryScalarWhereInput[]
  id?: Prisma.StringFilter<"Category"> | string
  tournamentId?: Prisma.StringNullableFilter<"Category"> | string | null
  age?: Prisma.StringFilter<"Category"> | string
  weight?: Prisma.StringFilter<"Category"> | string
}

export type CategoryCreateWithoutMatchesInput = {
  id?: string
  age: string
  weight: string
  tournament?: Prisma.TournamentCreateNestedOneWithoutCategoriesInput
  fighters?: Prisma.FighterCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutMatchesInput = {
  id?: string
  tournamentId?: string | null
  age: string
  weight: string
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutMatchesInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutMatchesInput, Prisma.CategoryUncheckedCreateWithoutMatchesInput>
}

export type CategoryUpsertWithoutMatchesInput = {
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutMatchesInput, Prisma.CategoryUncheckedUpdateWithoutMatchesInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutMatchesInput, Prisma.CategoryUncheckedCreateWithoutMatchesInput>
  where?: Prisma.CategoryWhereInput
}

export type CategoryUpdateToOneWithWhereWithoutMatchesInput = {
  where?: Prisma.CategoryWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutMatchesInput, Prisma.CategoryUncheckedUpdateWithoutMatchesInput>
}

export type CategoryUpdateWithoutMatchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  tournament?: Prisma.TournamentUpdateOneWithoutCategoriesNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutMatchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateWithoutFightersInput = {
  id?: string
  age: string
  weight: string
  tournament?: Prisma.TournamentCreateNestedOneWithoutCategoriesInput
  matches?: Prisma.MatchCreateNestedManyWithoutCategoryInput
}

export type CategoryUncheckedCreateWithoutFightersInput = {
  id?: string
  tournamentId?: string | null
  age: string
  weight: string
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutCategoryInput
}

export type CategoryCreateOrConnectWithoutFightersInput = {
  where: Prisma.CategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.CategoryCreateWithoutFightersInput, Prisma.CategoryUncheckedCreateWithoutFightersInput>
}

export type CategoryUpsertWithoutFightersInput = {
  update: Prisma.XOR<Prisma.CategoryUpdateWithoutFightersInput, Prisma.CategoryUncheckedUpdateWithoutFightersInput>
  create: Prisma.XOR<Prisma.CategoryCreateWithoutFightersInput, Prisma.CategoryUncheckedCreateWithoutFightersInput>
  where?: Prisma.CategoryWhereInput
}

export type CategoryUpdateToOneWithWhereWithoutFightersInput = {
  where?: Prisma.CategoryWhereInput
  data: Prisma.XOR<Prisma.CategoryUpdateWithoutFightersInput, Prisma.CategoryUncheckedUpdateWithoutFightersInput>
}

export type CategoryUpdateWithoutFightersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  tournament?: Prisma.TournamentUpdateOneWithoutCategoriesNestedInput
  matches?: Prisma.MatchUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutFightersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  matches?: Prisma.MatchUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryCreateManyTournamentInput = {
  id?: string
  age: string
  weight: string
}

export type CategoryUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  fighters?: Prisma.FighterUpdateManyWithoutCategoryNestedInput
  matches?: Prisma.MatchUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutCategoryNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutCategoryNestedInput
}

export type CategoryUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  age?: Prisma.StringFieldUpdateOperationsInput | string
  weight?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type CategoryCountOutputType
 */

export type CategoryCountOutputType = {
  fighters: number
  matches: number
}

export type CategoryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fighters?: boolean | CategoryCountOutputTypeCountFightersArgs
  matches?: boolean | CategoryCountOutputTypeCountMatchesArgs
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CategoryCountOutputType
   */
  select?: Prisma.CategoryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeCountFightersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FighterWhereInput
}

/**
 * CategoryCountOutputType without action
 */
export type CategoryCountOutputTypeCountMatchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchWhereInput
}


export type CategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  age?: boolean
  weight?: boolean
  tournament?: boolean | Prisma.Category$tournamentArgs<ExtArgs>
  fighters?: boolean | Prisma.Category$fightersArgs<ExtArgs>
  matches?: boolean | Prisma.Category$matchesArgs<ExtArgs>
  _count?: boolean | Prisma.CategoryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["category"]>

export type CategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  age?: boolean
  weight?: boolean
  tournament?: boolean | Prisma.Category$tournamentArgs<ExtArgs>
}, ExtArgs["result"]["category"]>

export type CategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  age?: boolean
  weight?: boolean
  tournament?: boolean | Prisma.Category$tournamentArgs<ExtArgs>
}, ExtArgs["result"]["category"]>

export type CategorySelectScalar = {
  id?: boolean
  tournamentId?: boolean
  age?: boolean
  weight?: boolean
}

export type CategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "age" | "weight", ExtArgs["result"]["category"]>
export type CategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.Category$tournamentArgs<ExtArgs>
  fighters?: boolean | Prisma.Category$fightersArgs<ExtArgs>
  matches?: boolean | Prisma.Category$matchesArgs<ExtArgs>
  _count?: boolean | Prisma.CategoryCountOutputTypeDefaultArgs<ExtArgs>
}
export type CategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.Category$tournamentArgs<ExtArgs>
}
export type CategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.Category$tournamentArgs<ExtArgs>
}

export type $CategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Category"
  objects: {
    tournament: Prisma.$TournamentPayload<ExtArgs> | null
    fighters: Prisma.$FighterPayload<ExtArgs>[]
    matches: Prisma.$MatchPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tournamentId: string | null
    age: string
    weight: string
  }, ExtArgs["result"]["category"]>
  composites: {}
}

export type CategoryGetPayload<S extends boolean | null | undefined | CategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CategoryPayload, S>

export type CategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CategoryCountAggregateInputType | true
  }

export interface CategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Category'], meta: { name: 'Category' } }
  /**
   * Find zero or one Category that matches the filter.
   * @param {CategoryFindUniqueArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, CategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Category that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CategoryFindUniqueOrThrowArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Category that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryFindFirstArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, CategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Category that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryFindFirstOrThrowArgs} args - Arguments to find a Category
   * @example
   * // Get one Category
   * const category = await prisma.category.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Categories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Categories
   * const categories = await prisma.category.findMany()
   * 
   * // Get first 10 Categories
   * const categories = await prisma.category.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const categoryWithIdOnly = await prisma.category.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CategoryFindManyArgs>(args?: Prisma.SelectSubset<T, CategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Category.
   * @param {CategoryCreateArgs} args - Arguments to create a Category.
   * @example
   * // Create one Category
   * const Category = await prisma.category.create({
   *   data: {
   *     // ... data to create a Category
   *   }
   * })
   * 
   */
  create<T extends CategoryCreateArgs>(args: Prisma.SelectSubset<T, CategoryCreateArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Categories.
   * @param {CategoryCreateManyArgs} args - Arguments to create many Categories.
   * @example
   * // Create many Categories
   * const category = await prisma.category.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, CategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Categories and returns the data saved in the database.
   * @param {CategoryCreateManyAndReturnArgs} args - Arguments to create many Categories.
   * @example
   * // Create many Categories
   * const category = await prisma.category.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Categories and only return the `id`
   * const categoryWithIdOnly = await prisma.category.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Category.
   * @param {CategoryDeleteArgs} args - Arguments to delete one Category.
   * @example
   * // Delete one Category
   * const Category = await prisma.category.delete({
   *   where: {
   *     // ... filter to delete one Category
   *   }
   * })
   * 
   */
  delete<T extends CategoryDeleteArgs>(args: Prisma.SelectSubset<T, CategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Category.
   * @param {CategoryUpdateArgs} args - Arguments to update one Category.
   * @example
   * // Update one Category
   * const category = await prisma.category.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CategoryUpdateArgs>(args: Prisma.SelectSubset<T, CategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Categories.
   * @param {CategoryDeleteManyArgs} args - Arguments to filter Categories to delete.
   * @example
   * // Delete a few Categories
   * const { count } = await prisma.category.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, CategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Categories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Categories
   * const category = await prisma.category.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, CategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Categories and returns the data updated in the database.
   * @param {CategoryUpdateManyAndReturnArgs} args - Arguments to update many Categories.
   * @example
   * // Update many Categories
   * const category = await prisma.category.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Categories and only return the `id`
   * const categoryWithIdOnly = await prisma.category.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Category.
   * @param {CategoryUpsertArgs} args - Arguments to update or create a Category.
   * @example
   * // Update or create a Category
   * const category = await prisma.category.upsert({
   *   create: {
   *     // ... data to create a Category
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Category we want to update
   *   }
   * })
   */
  upsert<T extends CategoryUpsertArgs>(args: Prisma.SelectSubset<T, CategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Categories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryCountArgs} args - Arguments to filter Categories to count.
   * @example
   * // Count the number of Categories
   * const count = await prisma.category.count({
   *   where: {
   *     // ... the filter for the Categories we want to count
   *   }
   * })
  **/
  count<T extends CategoryCountArgs>(
    args?: Prisma.Subset<T, CategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Category.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CategoryAggregateArgs>(args: Prisma.Subset<T, CategoryAggregateArgs>): Prisma.PrismaPromise<GetCategoryAggregateType<T>>

  /**
   * Group by Category.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CategoryGroupByArgs['orderBy'] }
      : { orderBy?: CategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Category model
 */
readonly fields: CategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Category.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tournament<T extends Prisma.Category$tournamentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$tournamentArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  fighters<T extends Prisma.Category$fightersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$fightersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  matches<T extends Prisma.Category$matchesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Category$matchesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Category model
 */
export interface CategoryFieldRefs {
  readonly id: Prisma.FieldRef<"Category", 'String'>
  readonly tournamentId: Prisma.FieldRef<"Category", 'String'>
  readonly age: Prisma.FieldRef<"Category", 'String'>
  readonly weight: Prisma.FieldRef<"Category", 'String'>
}
    

// Custom InputTypes
/**
 * Category findUnique
 */
export type CategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category findUniqueOrThrow
 */
export type CategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category findFirst
 */
export type CategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Categories.
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Categories.
   */
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Category findFirstOrThrow
 */
export type CategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Category to fetch.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Categories.
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Categories.
   */
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Category findMany
 */
export type CategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter, which Categories to fetch.
   */
  where?: Prisma.CategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Categories to fetch.
   */
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Categories.
   */
  cursor?: Prisma.CategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Categories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Categories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Categories.
   */
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Category create
 */
export type CategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a Category.
   */
  data: Prisma.XOR<Prisma.CategoryCreateInput, Prisma.CategoryUncheckedCreateInput>
}

/**
 * Category createMany
 */
export type CategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Categories.
   */
  data: Prisma.CategoryCreateManyInput | Prisma.CategoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Category createManyAndReturn
 */
export type CategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * The data used to create many Categories.
   */
  data: Prisma.CategoryCreateManyInput | Prisma.CategoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Category update
 */
export type CategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a Category.
   */
  data: Prisma.XOR<Prisma.CategoryUpdateInput, Prisma.CategoryUncheckedUpdateInput>
  /**
   * Choose, which Category to update.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category updateMany
 */
export type CategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Categories.
   */
  data: Prisma.XOR<Prisma.CategoryUpdateManyMutationInput, Prisma.CategoryUncheckedUpdateManyInput>
  /**
   * Filter which Categories to update
   */
  where?: Prisma.CategoryWhereInput
  /**
   * Limit how many Categories to update.
   */
  limit?: number
}

/**
 * Category updateManyAndReturn
 */
export type CategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * The data used to update Categories.
   */
  data: Prisma.XOR<Prisma.CategoryUpdateManyMutationInput, Prisma.CategoryUncheckedUpdateManyInput>
  /**
   * Filter which Categories to update
   */
  where?: Prisma.CategoryWhereInput
  /**
   * Limit how many Categories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Category upsert
 */
export type CategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the Category to update in case it exists.
   */
  where: Prisma.CategoryWhereUniqueInput
  /**
   * In case the Category found by the `where` argument doesn't exist, create a new Category with this data.
   */
  create: Prisma.XOR<Prisma.CategoryCreateInput, Prisma.CategoryUncheckedCreateInput>
  /**
   * In case the Category was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CategoryUpdateInput, Prisma.CategoryUncheckedUpdateInput>
}

/**
 * Category delete
 */
export type CategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  /**
   * Filter which Category to delete.
   */
  where: Prisma.CategoryWhereUniqueInput
}

/**
 * Category deleteMany
 */
export type CategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Categories to delete
   */
  where?: Prisma.CategoryWhereInput
  /**
   * Limit how many Categories to delete.
   */
  limit?: number
}

/**
 * Category.tournament
 */
export type Category$tournamentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  where?: Prisma.TournamentWhereInput
}

/**
 * Category.fighters
 */
export type Category$fightersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  where?: Prisma.FighterWhereInput
  orderBy?: Prisma.FighterOrderByWithRelationInput | Prisma.FighterOrderByWithRelationInput[]
  cursor?: Prisma.FighterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FighterScalarFieldEnum | Prisma.FighterScalarFieldEnum[]
}

/**
 * Category.matches
 */
export type Category$matchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  where?: Prisma.MatchWhereInput
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  cursor?: Prisma.MatchWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Category without action
 */
export type CategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
}
