
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Fighter` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Fighter
 * 
 */
export type FighterModel = runtime.Types.Result.DefaultSelection<Prisma.$FighterPayload>

export type AggregateFighter = {
  _count: FighterCountAggregateOutputType | null
  _avg: FighterAvgAggregateOutputType | null
  _sum: FighterSumAggregateOutputType | null
  _min: FighterMinAggregateOutputType | null
  _max: FighterMaxAggregateOutputType | null
}

export type FighterAvgAggregateOutputType = {
  id: number | null
  order: number | null
  weight: number | null
  clubId: number | null
}

export type FighterSumAggregateOutputType = {
  id: number | null
  order: number | null
  weight: number | null
  clubId: number | null
}

export type FighterMinAggregateOutputType = {
  id: number | null
  categoryId: string | null
  tournamentId: string | null
  order: number | null
  name: string | null
  birthday: Date | null
  weight: number | null
  clubId: number | null
}

export type FighterMaxAggregateOutputType = {
  id: number | null
  categoryId: string | null
  tournamentId: string | null
  order: number | null
  name: string | null
  birthday: Date | null
  weight: number | null
  clubId: number | null
}

export type FighterCountAggregateOutputType = {
  id: number
  categoryId: number
  tournamentId: number
  order: number
  name: number
  birthday: number
  weight: number
  clubId: number
  _all: number
}


export type FighterAvgAggregateInputType = {
  id?: true
  order?: true
  weight?: true
  clubId?: true
}

export type FighterSumAggregateInputType = {
  id?: true
  order?: true
  weight?: true
  clubId?: true
}

export type FighterMinAggregateInputType = {
  id?: true
  categoryId?: true
  tournamentId?: true
  order?: true
  name?: true
  birthday?: true
  weight?: true
  clubId?: true
}

export type FighterMaxAggregateInputType = {
  id?: true
  categoryId?: true
  tournamentId?: true
  order?: true
  name?: true
  birthday?: true
  weight?: true
  clubId?: true
}

export type FighterCountAggregateInputType = {
  id?: true
  categoryId?: true
  tournamentId?: true
  order?: true
  name?: true
  birthday?: true
  weight?: true
  clubId?: true
  _all?: true
}

export type FighterAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Fighter to aggregate.
   */
  where?: Prisma.FighterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fighters to fetch.
   */
  orderBy?: Prisma.FighterOrderByWithRelationInput | Prisma.FighterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FighterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fighters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fighters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Fighters
  **/
  _count?: true | FighterCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FighterAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FighterSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FighterMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FighterMaxAggregateInputType
}

export type GetFighterAggregateType<T extends FighterAggregateArgs> = {
      [P in keyof T & keyof AggregateFighter]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFighter[P]>
    : Prisma.GetScalarType<T[P], AggregateFighter[P]>
}




export type FighterGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FighterWhereInput
  orderBy?: Prisma.FighterOrderByWithAggregationInput | Prisma.FighterOrderByWithAggregationInput[]
  by: Prisma.FighterScalarFieldEnum[] | Prisma.FighterScalarFieldEnum
  having?: Prisma.FighterScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FighterCountAggregateInputType | true
  _avg?: FighterAvgAggregateInputType
  _sum?: FighterSumAggregateInputType
  _min?: FighterMinAggregateInputType
  _max?: FighterMaxAggregateInputType
}

export type FighterGroupByOutputType = {
  id: number
  categoryId: string | null
  tournamentId: string | null
  order: number
  name: string
  birthday: Date
  weight: number
  clubId: number | null
  _count: FighterCountAggregateOutputType | null
  _avg: FighterAvgAggregateOutputType | null
  _sum: FighterSumAggregateOutputType | null
  _min: FighterMinAggregateOutputType | null
  _max: FighterMaxAggregateOutputType | null
}

export type GetFighterGroupByPayload<T extends FighterGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FighterGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FighterGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FighterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FighterGroupByOutputType[P]>
      }
    >
  >



export type FighterWhereInput = {
  AND?: Prisma.FighterWhereInput | Prisma.FighterWhereInput[]
  OR?: Prisma.FighterWhereInput[]
  NOT?: Prisma.FighterWhereInput | Prisma.FighterWhereInput[]
  id?: Prisma.IntFilter<"Fighter"> | number
  categoryId?: Prisma.StringNullableFilter<"Fighter"> | string | null
  tournamentId?: Prisma.StringNullableFilter<"Fighter"> | string | null
  order?: Prisma.IntFilter<"Fighter"> | number
  name?: Prisma.StringFilter<"Fighter"> | string
  birthday?: Prisma.DateTimeFilter<"Fighter"> | Date | string
  weight?: Prisma.FloatFilter<"Fighter"> | number
  clubId?: Prisma.IntNullableFilter<"Fighter"> | number | null
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  club?: Prisma.XOR<Prisma.ClubNullableScalarRelationFilter, Prisma.ClubWhereInput> | null
  matchesAsFighter1?: Prisma.MatchListRelationFilter
  matchesAsFighter2?: Prisma.MatchListRelationFilter
}

export type FighterOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birthday?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
  tournament?: Prisma.TournamentOrderByWithRelationInput
  club?: Prisma.ClubOrderByWithRelationInput
  matchesAsFighter1?: Prisma.MatchOrderByRelationAggregateInput
  matchesAsFighter2?: Prisma.MatchOrderByRelationAggregateInput
}

export type FighterWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.FighterWhereInput | Prisma.FighterWhereInput[]
  OR?: Prisma.FighterWhereInput[]
  NOT?: Prisma.FighterWhereInput | Prisma.FighterWhereInput[]
  categoryId?: Prisma.StringNullableFilter<"Fighter"> | string | null
  tournamentId?: Prisma.StringNullableFilter<"Fighter"> | string | null
  order?: Prisma.IntFilter<"Fighter"> | number
  name?: Prisma.StringFilter<"Fighter"> | string
  birthday?: Prisma.DateTimeFilter<"Fighter"> | Date | string
  weight?: Prisma.FloatFilter<"Fighter"> | number
  clubId?: Prisma.IntNullableFilter<"Fighter"> | number | null
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  club?: Prisma.XOR<Prisma.ClubNullableScalarRelationFilter, Prisma.ClubWhereInput> | null
  matchesAsFighter1?: Prisma.MatchListRelationFilter
  matchesAsFighter2?: Prisma.MatchListRelationFilter
}, "id">

export type FighterOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birthday?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FighterCountOrderByAggregateInput
  _avg?: Prisma.FighterAvgOrderByAggregateInput
  _max?: Prisma.FighterMaxOrderByAggregateInput
  _min?: Prisma.FighterMinOrderByAggregateInput
  _sum?: Prisma.FighterSumOrderByAggregateInput
}

export type FighterScalarWhereWithAggregatesInput = {
  AND?: Prisma.FighterScalarWhereWithAggregatesInput | Prisma.FighterScalarWhereWithAggregatesInput[]
  OR?: Prisma.FighterScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FighterScalarWhereWithAggregatesInput | Prisma.FighterScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Fighter"> | number
  categoryId?: Prisma.StringNullableWithAggregatesFilter<"Fighter"> | string | null
  tournamentId?: Prisma.StringNullableWithAggregatesFilter<"Fighter"> | string | null
  order?: Prisma.IntWithAggregatesFilter<"Fighter"> | number
  name?: Prisma.StringWithAggregatesFilter<"Fighter"> | string
  birthday?: Prisma.DateTimeWithAggregatesFilter<"Fighter"> | Date | string
  weight?: Prisma.FloatWithAggregatesFilter<"Fighter"> | number
  clubId?: Prisma.IntNullableWithAggregatesFilter<"Fighter"> | number | null
}

export type FighterCreateInput = {
  order: number
  name: string
  birthday: Date | string
  weight: number
  category?: Prisma.CategoryCreateNestedOneWithoutFightersInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutFightersInput
  club?: Prisma.ClubCreateNestedOneWithoutFightersInput
  matchesAsFighter1?: Prisma.MatchCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchCreateNestedManyWithoutFighter2Input
}

export type FighterUncheckedCreateInput = {
  id?: number
  categoryId?: string | null
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
  matchesAsFighter1?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter2Input
}

export type FighterUpdateInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  category?: Prisma.CategoryUpdateOneWithoutFightersNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutFightersNestedInput
  club?: Prisma.ClubUpdateOneWithoutFightersNestedInput
  matchesAsFighter1?: Prisma.MatchUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  matchesAsFighter1?: Prisma.MatchUncheckedUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUncheckedUpdateManyWithoutFighter2NestedInput
}

export type FighterCreateManyInput = {
  id?: number
  categoryId?: string | null
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
}

export type FighterUpdateManyMutationInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type FighterUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type FighterListRelationFilter = {
  every?: Prisma.FighterWhereInput
  some?: Prisma.FighterWhereInput
  none?: Prisma.FighterWhereInput
}

export type FighterOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FighterNullableScalarRelationFilter = {
  is?: Prisma.FighterWhereInput | null
  isNot?: Prisma.FighterWhereInput | null
}

export type FighterCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birthday?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type FighterAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type FighterMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birthday?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type FighterMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  birthday?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type FighterSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  clubId?: Prisma.SortOrder
}

export type FighterCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutTournamentInput, Prisma.FighterUncheckedCreateWithoutTournamentInput> | Prisma.FighterCreateWithoutTournamentInput[] | Prisma.FighterUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutTournamentInput | Prisma.FighterCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.FighterCreateManyTournamentInputEnvelope
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
}

export type FighterUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutTournamentInput, Prisma.FighterUncheckedCreateWithoutTournamentInput> | Prisma.FighterCreateWithoutTournamentInput[] | Prisma.FighterUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutTournamentInput | Prisma.FighterCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.FighterCreateManyTournamentInputEnvelope
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
}

export type FighterUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutTournamentInput, Prisma.FighterUncheckedCreateWithoutTournamentInput> | Prisma.FighterCreateWithoutTournamentInput[] | Prisma.FighterUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutTournamentInput | Prisma.FighterCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.FighterUpsertWithWhereUniqueWithoutTournamentInput | Prisma.FighterUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.FighterCreateManyTournamentInputEnvelope
  set?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  disconnect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  delete?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  update?: Prisma.FighterUpdateWithWhereUniqueWithoutTournamentInput | Prisma.FighterUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.FighterUpdateManyWithWhereWithoutTournamentInput | Prisma.FighterUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
}

export type FighterUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutTournamentInput, Prisma.FighterUncheckedCreateWithoutTournamentInput> | Prisma.FighterCreateWithoutTournamentInput[] | Prisma.FighterUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutTournamentInput | Prisma.FighterCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.FighterUpsertWithWhereUniqueWithoutTournamentInput | Prisma.FighterUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.FighterCreateManyTournamentInputEnvelope
  set?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  disconnect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  delete?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  update?: Prisma.FighterUpdateWithWhereUniqueWithoutTournamentInput | Prisma.FighterUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.FighterUpdateManyWithWhereWithoutTournamentInput | Prisma.FighterUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
}

export type FighterCreateNestedManyWithoutClubInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutClubInput, Prisma.FighterUncheckedCreateWithoutClubInput> | Prisma.FighterCreateWithoutClubInput[] | Prisma.FighterUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutClubInput | Prisma.FighterCreateOrConnectWithoutClubInput[]
  createMany?: Prisma.FighterCreateManyClubInputEnvelope
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
}

export type FighterUncheckedCreateNestedManyWithoutClubInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutClubInput, Prisma.FighterUncheckedCreateWithoutClubInput> | Prisma.FighterCreateWithoutClubInput[] | Prisma.FighterUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutClubInput | Prisma.FighterCreateOrConnectWithoutClubInput[]
  createMany?: Prisma.FighterCreateManyClubInputEnvelope
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
}

export type FighterUpdateManyWithoutClubNestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutClubInput, Prisma.FighterUncheckedCreateWithoutClubInput> | Prisma.FighterCreateWithoutClubInput[] | Prisma.FighterUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutClubInput | Prisma.FighterCreateOrConnectWithoutClubInput[]
  upsert?: Prisma.FighterUpsertWithWhereUniqueWithoutClubInput | Prisma.FighterUpsertWithWhereUniqueWithoutClubInput[]
  createMany?: Prisma.FighterCreateManyClubInputEnvelope
  set?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  disconnect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  delete?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  update?: Prisma.FighterUpdateWithWhereUniqueWithoutClubInput | Prisma.FighterUpdateWithWhereUniqueWithoutClubInput[]
  updateMany?: Prisma.FighterUpdateManyWithWhereWithoutClubInput | Prisma.FighterUpdateManyWithWhereWithoutClubInput[]
  deleteMany?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
}

export type FighterUncheckedUpdateManyWithoutClubNestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutClubInput, Prisma.FighterUncheckedCreateWithoutClubInput> | Prisma.FighterCreateWithoutClubInput[] | Prisma.FighterUncheckedCreateWithoutClubInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutClubInput | Prisma.FighterCreateOrConnectWithoutClubInput[]
  upsert?: Prisma.FighterUpsertWithWhereUniqueWithoutClubInput | Prisma.FighterUpsertWithWhereUniqueWithoutClubInput[]
  createMany?: Prisma.FighterCreateManyClubInputEnvelope
  set?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  disconnect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  delete?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  update?: Prisma.FighterUpdateWithWhereUniqueWithoutClubInput | Prisma.FighterUpdateWithWhereUniqueWithoutClubInput[]
  updateMany?: Prisma.FighterUpdateManyWithWhereWithoutClubInput | Prisma.FighterUpdateManyWithWhereWithoutClubInput[]
  deleteMany?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
}

export type FighterCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutCategoryInput, Prisma.FighterUncheckedCreateWithoutCategoryInput> | Prisma.FighterCreateWithoutCategoryInput[] | Prisma.FighterUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutCategoryInput | Prisma.FighterCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.FighterCreateManyCategoryInputEnvelope
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
}

export type FighterUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutCategoryInput, Prisma.FighterUncheckedCreateWithoutCategoryInput> | Prisma.FighterCreateWithoutCategoryInput[] | Prisma.FighterUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutCategoryInput | Prisma.FighterCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.FighterCreateManyCategoryInputEnvelope
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
}

export type FighterUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutCategoryInput, Prisma.FighterUncheckedCreateWithoutCategoryInput> | Prisma.FighterCreateWithoutCategoryInput[] | Prisma.FighterUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutCategoryInput | Prisma.FighterCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.FighterUpsertWithWhereUniqueWithoutCategoryInput | Prisma.FighterUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.FighterCreateManyCategoryInputEnvelope
  set?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  disconnect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  delete?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  update?: Prisma.FighterUpdateWithWhereUniqueWithoutCategoryInput | Prisma.FighterUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.FighterUpdateManyWithWhereWithoutCategoryInput | Prisma.FighterUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
}

export type FighterUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutCategoryInput, Prisma.FighterUncheckedCreateWithoutCategoryInput> | Prisma.FighterCreateWithoutCategoryInput[] | Prisma.FighterUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutCategoryInput | Prisma.FighterCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.FighterUpsertWithWhereUniqueWithoutCategoryInput | Prisma.FighterUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.FighterCreateManyCategoryInputEnvelope
  set?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  disconnect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  delete?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  connect?: Prisma.FighterWhereUniqueInput | Prisma.FighterWhereUniqueInput[]
  update?: Prisma.FighterUpdateWithWhereUniqueWithoutCategoryInput | Prisma.FighterUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.FighterUpdateManyWithWhereWithoutCategoryInput | Prisma.FighterUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
}

export type FighterCreateNestedOneWithoutMatchesAsFighter1Input = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter1Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter1Input>
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutMatchesAsFighter1Input
  connect?: Prisma.FighterWhereUniqueInput
}

export type FighterCreateNestedOneWithoutMatchesAsFighter2Input = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter2Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter2Input>
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutMatchesAsFighter2Input
  connect?: Prisma.FighterWhereUniqueInput
}

export type FighterUpdateOneWithoutMatchesAsFighter1NestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter1Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter1Input>
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutMatchesAsFighter1Input
  upsert?: Prisma.FighterUpsertWithoutMatchesAsFighter1Input
  disconnect?: Prisma.FighterWhereInput | boolean
  delete?: Prisma.FighterWhereInput | boolean
  connect?: Prisma.FighterWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FighterUpdateToOneWithWhereWithoutMatchesAsFighter1Input, Prisma.FighterUpdateWithoutMatchesAsFighter1Input>, Prisma.FighterUncheckedUpdateWithoutMatchesAsFighter1Input>
}

export type FighterUpdateOneWithoutMatchesAsFighter2NestedInput = {
  create?: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter2Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter2Input>
  connectOrCreate?: Prisma.FighterCreateOrConnectWithoutMatchesAsFighter2Input
  upsert?: Prisma.FighterUpsertWithoutMatchesAsFighter2Input
  disconnect?: Prisma.FighterWhereInput | boolean
  delete?: Prisma.FighterWhereInput | boolean
  connect?: Prisma.FighterWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FighterUpdateToOneWithWhereWithoutMatchesAsFighter2Input, Prisma.FighterUpdateWithoutMatchesAsFighter2Input>, Prisma.FighterUncheckedUpdateWithoutMatchesAsFighter2Input>
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FighterCreateWithoutTournamentInput = {
  order: number
  name: string
  birthday: Date | string
  weight: number
  category?: Prisma.CategoryCreateNestedOneWithoutFightersInput
  club?: Prisma.ClubCreateNestedOneWithoutFightersInput
  matchesAsFighter1?: Prisma.MatchCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchCreateNestedManyWithoutFighter2Input
}

export type FighterUncheckedCreateWithoutTournamentInput = {
  id?: number
  categoryId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
  matchesAsFighter1?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter2Input
}

export type FighterCreateOrConnectWithoutTournamentInput = {
  where: Prisma.FighterWhereUniqueInput
  create: Prisma.XOR<Prisma.FighterCreateWithoutTournamentInput, Prisma.FighterUncheckedCreateWithoutTournamentInput>
}

export type FighterCreateManyTournamentInputEnvelope = {
  data: Prisma.FighterCreateManyTournamentInput | Prisma.FighterCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type FighterUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.FighterWhereUniqueInput
  update: Prisma.XOR<Prisma.FighterUpdateWithoutTournamentInput, Prisma.FighterUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.FighterCreateWithoutTournamentInput, Prisma.FighterUncheckedCreateWithoutTournamentInput>
}

export type FighterUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.FighterWhereUniqueInput
  data: Prisma.XOR<Prisma.FighterUpdateWithoutTournamentInput, Prisma.FighterUncheckedUpdateWithoutTournamentInput>
}

export type FighterUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.FighterScalarWhereInput
  data: Prisma.XOR<Prisma.FighterUpdateManyMutationInput, Prisma.FighterUncheckedUpdateManyWithoutTournamentInput>
}

export type FighterScalarWhereInput = {
  AND?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
  OR?: Prisma.FighterScalarWhereInput[]
  NOT?: Prisma.FighterScalarWhereInput | Prisma.FighterScalarWhereInput[]
  id?: Prisma.IntFilter<"Fighter"> | number
  categoryId?: Prisma.StringNullableFilter<"Fighter"> | string | null
  tournamentId?: Prisma.StringNullableFilter<"Fighter"> | string | null
  order?: Prisma.IntFilter<"Fighter"> | number
  name?: Prisma.StringFilter<"Fighter"> | string
  birthday?: Prisma.DateTimeFilter<"Fighter"> | Date | string
  weight?: Prisma.FloatFilter<"Fighter"> | number
  clubId?: Prisma.IntNullableFilter<"Fighter"> | number | null
}

export type FighterCreateWithoutClubInput = {
  order: number
  name: string
  birthday: Date | string
  weight: number
  category?: Prisma.CategoryCreateNestedOneWithoutFightersInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutFightersInput
  matchesAsFighter1?: Prisma.MatchCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchCreateNestedManyWithoutFighter2Input
}

export type FighterUncheckedCreateWithoutClubInput = {
  id?: number
  categoryId?: string | null
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  matchesAsFighter1?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter2Input
}

export type FighterCreateOrConnectWithoutClubInput = {
  where: Prisma.FighterWhereUniqueInput
  create: Prisma.XOR<Prisma.FighterCreateWithoutClubInput, Prisma.FighterUncheckedCreateWithoutClubInput>
}

export type FighterCreateManyClubInputEnvelope = {
  data: Prisma.FighterCreateManyClubInput | Prisma.FighterCreateManyClubInput[]
  skipDuplicates?: boolean
}

export type FighterUpsertWithWhereUniqueWithoutClubInput = {
  where: Prisma.FighterWhereUniqueInput
  update: Prisma.XOR<Prisma.FighterUpdateWithoutClubInput, Prisma.FighterUncheckedUpdateWithoutClubInput>
  create: Prisma.XOR<Prisma.FighterCreateWithoutClubInput, Prisma.FighterUncheckedCreateWithoutClubInput>
}

export type FighterUpdateWithWhereUniqueWithoutClubInput = {
  where: Prisma.FighterWhereUniqueInput
  data: Prisma.XOR<Prisma.FighterUpdateWithoutClubInput, Prisma.FighterUncheckedUpdateWithoutClubInput>
}

export type FighterUpdateManyWithWhereWithoutClubInput = {
  where: Prisma.FighterScalarWhereInput
  data: Prisma.XOR<Prisma.FighterUpdateManyMutationInput, Prisma.FighterUncheckedUpdateManyWithoutClubInput>
}

export type FighterCreateWithoutCategoryInput = {
  order: number
  name: string
  birthday: Date | string
  weight: number
  tournament?: Prisma.TournamentCreateNestedOneWithoutFightersInput
  club?: Prisma.ClubCreateNestedOneWithoutFightersInput
  matchesAsFighter1?: Prisma.MatchCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchCreateNestedManyWithoutFighter2Input
}

export type FighterUncheckedCreateWithoutCategoryInput = {
  id?: number
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
  matchesAsFighter1?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter1Input
  matchesAsFighter2?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter2Input
}

export type FighterCreateOrConnectWithoutCategoryInput = {
  where: Prisma.FighterWhereUniqueInput
  create: Prisma.XOR<Prisma.FighterCreateWithoutCategoryInput, Prisma.FighterUncheckedCreateWithoutCategoryInput>
}

export type FighterCreateManyCategoryInputEnvelope = {
  data: Prisma.FighterCreateManyCategoryInput | Prisma.FighterCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type FighterUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.FighterWhereUniqueInput
  update: Prisma.XOR<Prisma.FighterUpdateWithoutCategoryInput, Prisma.FighterUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.FighterCreateWithoutCategoryInput, Prisma.FighterUncheckedCreateWithoutCategoryInput>
}

export type FighterUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.FighterWhereUniqueInput
  data: Prisma.XOR<Prisma.FighterUpdateWithoutCategoryInput, Prisma.FighterUncheckedUpdateWithoutCategoryInput>
}

export type FighterUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.FighterScalarWhereInput
  data: Prisma.XOR<Prisma.FighterUpdateManyMutationInput, Prisma.FighterUncheckedUpdateManyWithoutCategoryInput>
}

export type FighterCreateWithoutMatchesAsFighter1Input = {
  order: number
  name: string
  birthday: Date | string
  weight: number
  category?: Prisma.CategoryCreateNestedOneWithoutFightersInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutFightersInput
  club?: Prisma.ClubCreateNestedOneWithoutFightersInput
  matchesAsFighter2?: Prisma.MatchCreateNestedManyWithoutFighter2Input
}

export type FighterUncheckedCreateWithoutMatchesAsFighter1Input = {
  id?: number
  categoryId?: string | null
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
  matchesAsFighter2?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter2Input
}

export type FighterCreateOrConnectWithoutMatchesAsFighter1Input = {
  where: Prisma.FighterWhereUniqueInput
  create: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter1Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter1Input>
}

export type FighterCreateWithoutMatchesAsFighter2Input = {
  order: number
  name: string
  birthday: Date | string
  weight: number
  category?: Prisma.CategoryCreateNestedOneWithoutFightersInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutFightersInput
  club?: Prisma.ClubCreateNestedOneWithoutFightersInput
  matchesAsFighter1?: Prisma.MatchCreateNestedManyWithoutFighter1Input
}

export type FighterUncheckedCreateWithoutMatchesAsFighter2Input = {
  id?: number
  categoryId?: string | null
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
  matchesAsFighter1?: Prisma.MatchUncheckedCreateNestedManyWithoutFighter1Input
}

export type FighterCreateOrConnectWithoutMatchesAsFighter2Input = {
  where: Prisma.FighterWhereUniqueInput
  create: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter2Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter2Input>
}

export type FighterUpsertWithoutMatchesAsFighter1Input = {
  update: Prisma.XOR<Prisma.FighterUpdateWithoutMatchesAsFighter1Input, Prisma.FighterUncheckedUpdateWithoutMatchesAsFighter1Input>
  create: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter1Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter1Input>
  where?: Prisma.FighterWhereInput
}

export type FighterUpdateToOneWithWhereWithoutMatchesAsFighter1Input = {
  where?: Prisma.FighterWhereInput
  data: Prisma.XOR<Prisma.FighterUpdateWithoutMatchesAsFighter1Input, Prisma.FighterUncheckedUpdateWithoutMatchesAsFighter1Input>
}

export type FighterUpdateWithoutMatchesAsFighter1Input = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  category?: Prisma.CategoryUpdateOneWithoutFightersNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutFightersNestedInput
  club?: Prisma.ClubUpdateOneWithoutFightersNestedInput
  matchesAsFighter2?: Prisma.MatchUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateWithoutMatchesAsFighter1Input = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  matchesAsFighter2?: Prisma.MatchUncheckedUpdateManyWithoutFighter2NestedInput
}

export type FighterUpsertWithoutMatchesAsFighter2Input = {
  update: Prisma.XOR<Prisma.FighterUpdateWithoutMatchesAsFighter2Input, Prisma.FighterUncheckedUpdateWithoutMatchesAsFighter2Input>
  create: Prisma.XOR<Prisma.FighterCreateWithoutMatchesAsFighter2Input, Prisma.FighterUncheckedCreateWithoutMatchesAsFighter2Input>
  where?: Prisma.FighterWhereInput
}

export type FighterUpdateToOneWithWhereWithoutMatchesAsFighter2Input = {
  where?: Prisma.FighterWhereInput
  data: Prisma.XOR<Prisma.FighterUpdateWithoutMatchesAsFighter2Input, Prisma.FighterUncheckedUpdateWithoutMatchesAsFighter2Input>
}

export type FighterUpdateWithoutMatchesAsFighter2Input = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  category?: Prisma.CategoryUpdateOneWithoutFightersNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutFightersNestedInput
  club?: Prisma.ClubUpdateOneWithoutFightersNestedInput
  matchesAsFighter1?: Prisma.MatchUpdateManyWithoutFighter1NestedInput
}

export type FighterUncheckedUpdateWithoutMatchesAsFighter2Input = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  matchesAsFighter1?: Prisma.MatchUncheckedUpdateManyWithoutFighter1NestedInput
}

export type FighterCreateManyTournamentInput = {
  id?: number
  categoryId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
}

export type FighterUpdateWithoutTournamentInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  category?: Prisma.CategoryUpdateOneWithoutFightersNestedInput
  club?: Prisma.ClubUpdateOneWithoutFightersNestedInput
  matchesAsFighter1?: Prisma.MatchUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  matchesAsFighter1?: Prisma.MatchUncheckedUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUncheckedUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type FighterCreateManyClubInput = {
  id?: number
  categoryId?: string | null
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
}

export type FighterUpdateWithoutClubInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  category?: Prisma.CategoryUpdateOneWithoutFightersNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutFightersNestedInput
  matchesAsFighter1?: Prisma.MatchUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateWithoutClubInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  matchesAsFighter1?: Prisma.MatchUncheckedUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUncheckedUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateManyWithoutClubInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type FighterCreateManyCategoryInput = {
  id?: number
  tournamentId?: string | null
  order: number
  name: string
  birthday: Date | string
  weight: number
  clubId?: number | null
}

export type FighterUpdateWithoutCategoryInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  tournament?: Prisma.TournamentUpdateOneWithoutFightersNestedInput
  club?: Prisma.ClubUpdateOneWithoutFightersNestedInput
  matchesAsFighter1?: Prisma.MatchUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  matchesAsFighter1?: Prisma.MatchUncheckedUpdateManyWithoutFighter1NestedInput
  matchesAsFighter2?: Prisma.MatchUncheckedUpdateManyWithoutFighter2NestedInput
}

export type FighterUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  birthday?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  clubId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type FighterCountOutputType
 */

export type FighterCountOutputType = {
  matchesAsFighter1: number
  matchesAsFighter2: number
}

export type FighterCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  matchesAsFighter1?: boolean | FighterCountOutputTypeCountMatchesAsFighter1Args
  matchesAsFighter2?: boolean | FighterCountOutputTypeCountMatchesAsFighter2Args
}

/**
 * FighterCountOutputType without action
 */
export type FighterCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FighterCountOutputType
   */
  select?: Prisma.FighterCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FighterCountOutputType without action
 */
export type FighterCountOutputTypeCountMatchesAsFighter1Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchWhereInput
}

/**
 * FighterCountOutputType without action
 */
export type FighterCountOutputTypeCountMatchesAsFighter2Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchWhereInput
}


export type FighterSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  order?: boolean
  name?: boolean
  birthday?: boolean
  weight?: boolean
  clubId?: boolean
  category?: boolean | Prisma.Fighter$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Fighter$tournamentArgs<ExtArgs>
  club?: boolean | Prisma.Fighter$clubArgs<ExtArgs>
  matchesAsFighter1?: boolean | Prisma.Fighter$matchesAsFighter1Args<ExtArgs>
  matchesAsFighter2?: boolean | Prisma.Fighter$matchesAsFighter2Args<ExtArgs>
  _count?: boolean | Prisma.FighterCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fighter"]>

export type FighterSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  order?: boolean
  name?: boolean
  birthday?: boolean
  weight?: boolean
  clubId?: boolean
  category?: boolean | Prisma.Fighter$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Fighter$tournamentArgs<ExtArgs>
  club?: boolean | Prisma.Fighter$clubArgs<ExtArgs>
}, ExtArgs["result"]["fighter"]>

export type FighterSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  order?: boolean
  name?: boolean
  birthday?: boolean
  weight?: boolean
  clubId?: boolean
  category?: boolean | Prisma.Fighter$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Fighter$tournamentArgs<ExtArgs>
  club?: boolean | Prisma.Fighter$clubArgs<ExtArgs>
}, ExtArgs["result"]["fighter"]>

export type FighterSelectScalar = {
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  order?: boolean
  name?: boolean
  birthday?: boolean
  weight?: boolean
  clubId?: boolean
}

export type FighterOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "categoryId" | "tournamentId" | "order" | "name" | "birthday" | "weight" | "clubId", ExtArgs["result"]["fighter"]>
export type FighterInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Fighter$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Fighter$tournamentArgs<ExtArgs>
  club?: boolean | Prisma.Fighter$clubArgs<ExtArgs>
  matchesAsFighter1?: boolean | Prisma.Fighter$matchesAsFighter1Args<ExtArgs>
  matchesAsFighter2?: boolean | Prisma.Fighter$matchesAsFighter2Args<ExtArgs>
  _count?: boolean | Prisma.FighterCountOutputTypeDefaultArgs<ExtArgs>
}
export type FighterIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Fighter$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Fighter$tournamentArgs<ExtArgs>
  club?: boolean | Prisma.Fighter$clubArgs<ExtArgs>
}
export type FighterIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Fighter$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Fighter$tournamentArgs<ExtArgs>
  club?: boolean | Prisma.Fighter$clubArgs<ExtArgs>
}

export type $FighterPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Fighter"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs> | null
    tournament: Prisma.$TournamentPayload<ExtArgs> | null
    club: Prisma.$ClubPayload<ExtArgs> | null
    matchesAsFighter1: Prisma.$MatchPayload<ExtArgs>[]
    matchesAsFighter2: Prisma.$MatchPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    categoryId: string | null
    tournamentId: string | null
    order: number
    name: string
    birthday: Date
    weight: number
    clubId: number | null
  }, ExtArgs["result"]["fighter"]>
  composites: {}
}

export type FighterGetPayload<S extends boolean | null | undefined | FighterDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FighterPayload, S>

export type FighterCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FighterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FighterCountAggregateInputType | true
  }

export interface FighterDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Fighter'], meta: { name: 'Fighter' } }
  /**
   * Find zero or one Fighter that matches the filter.
   * @param {FighterFindUniqueArgs} args - Arguments to find a Fighter
   * @example
   * // Get one Fighter
   * const fighter = await prisma.fighter.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FighterFindUniqueArgs>(args: Prisma.SelectSubset<T, FighterFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Fighter that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FighterFindUniqueOrThrowArgs} args - Arguments to find a Fighter
   * @example
   * // Get one Fighter
   * const fighter = await prisma.fighter.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FighterFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FighterFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Fighter that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterFindFirstArgs} args - Arguments to find a Fighter
   * @example
   * // Get one Fighter
   * const fighter = await prisma.fighter.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FighterFindFirstArgs>(args?: Prisma.SelectSubset<T, FighterFindFirstArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Fighter that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterFindFirstOrThrowArgs} args - Arguments to find a Fighter
   * @example
   * // Get one Fighter
   * const fighter = await prisma.fighter.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FighterFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FighterFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Fighters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Fighters
   * const fighters = await prisma.fighter.findMany()
   * 
   * // Get first 10 Fighters
   * const fighters = await prisma.fighter.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fighterWithIdOnly = await prisma.fighter.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FighterFindManyArgs>(args?: Prisma.SelectSubset<T, FighterFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Fighter.
   * @param {FighterCreateArgs} args - Arguments to create a Fighter.
   * @example
   * // Create one Fighter
   * const Fighter = await prisma.fighter.create({
   *   data: {
   *     // ... data to create a Fighter
   *   }
   * })
   * 
   */
  create<T extends FighterCreateArgs>(args: Prisma.SelectSubset<T, FighterCreateArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Fighters.
   * @param {FighterCreateManyArgs} args - Arguments to create many Fighters.
   * @example
   * // Create many Fighters
   * const fighter = await prisma.fighter.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FighterCreateManyArgs>(args?: Prisma.SelectSubset<T, FighterCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Fighters and returns the data saved in the database.
   * @param {FighterCreateManyAndReturnArgs} args - Arguments to create many Fighters.
   * @example
   * // Create many Fighters
   * const fighter = await prisma.fighter.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Fighters and only return the `id`
   * const fighterWithIdOnly = await prisma.fighter.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FighterCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FighterCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Fighter.
   * @param {FighterDeleteArgs} args - Arguments to delete one Fighter.
   * @example
   * // Delete one Fighter
   * const Fighter = await prisma.fighter.delete({
   *   where: {
   *     // ... filter to delete one Fighter
   *   }
   * })
   * 
   */
  delete<T extends FighterDeleteArgs>(args: Prisma.SelectSubset<T, FighterDeleteArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Fighter.
   * @param {FighterUpdateArgs} args - Arguments to update one Fighter.
   * @example
   * // Update one Fighter
   * const fighter = await prisma.fighter.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FighterUpdateArgs>(args: Prisma.SelectSubset<T, FighterUpdateArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Fighters.
   * @param {FighterDeleteManyArgs} args - Arguments to filter Fighters to delete.
   * @example
   * // Delete a few Fighters
   * const { count } = await prisma.fighter.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FighterDeleteManyArgs>(args?: Prisma.SelectSubset<T, FighterDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Fighters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Fighters
   * const fighter = await prisma.fighter.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FighterUpdateManyArgs>(args: Prisma.SelectSubset<T, FighterUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Fighters and returns the data updated in the database.
   * @param {FighterUpdateManyAndReturnArgs} args - Arguments to update many Fighters.
   * @example
   * // Update many Fighters
   * const fighter = await prisma.fighter.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Fighters and only return the `id`
   * const fighterWithIdOnly = await prisma.fighter.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FighterUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FighterUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Fighter.
   * @param {FighterUpsertArgs} args - Arguments to update or create a Fighter.
   * @example
   * // Update or create a Fighter
   * const fighter = await prisma.fighter.upsert({
   *   create: {
   *     // ... data to create a Fighter
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Fighter we want to update
   *   }
   * })
   */
  upsert<T extends FighterUpsertArgs>(args: Prisma.SelectSubset<T, FighterUpsertArgs<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Fighters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterCountArgs} args - Arguments to filter Fighters to count.
   * @example
   * // Count the number of Fighters
   * const count = await prisma.fighter.count({
   *   where: {
   *     // ... the filter for the Fighters we want to count
   *   }
   * })
  **/
  count<T extends FighterCountArgs>(
    args?: Prisma.Subset<T, FighterCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FighterCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Fighter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FighterAggregateArgs>(args: Prisma.Subset<T, FighterAggregateArgs>): Prisma.PrismaPromise<GetFighterAggregateType<T>>

  /**
   * Group by Fighter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FighterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FighterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FighterGroupByArgs['orderBy'] }
      : { orderBy?: FighterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FighterGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFighterGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Fighter model
 */
readonly fields: FighterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Fighter.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FighterClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.Fighter$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Fighter$categoryArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  tournament<T extends Prisma.Fighter$tournamentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Fighter$tournamentArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  club<T extends Prisma.Fighter$clubArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Fighter$clubArgs<ExtArgs>>): Prisma.Prisma__ClubClient<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  matchesAsFighter1<T extends Prisma.Fighter$matchesAsFighter1Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Fighter$matchesAsFighter1Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  matchesAsFighter2<T extends Prisma.Fighter$matchesAsFighter2Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Fighter$matchesAsFighter2Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Fighter model
 */
export interface FighterFieldRefs {
  readonly id: Prisma.FieldRef<"Fighter", 'Int'>
  readonly categoryId: Prisma.FieldRef<"Fighter", 'String'>
  readonly tournamentId: Prisma.FieldRef<"Fighter", 'String'>
  readonly order: Prisma.FieldRef<"Fighter", 'Int'>
  readonly name: Prisma.FieldRef<"Fighter", 'String'>
  readonly birthday: Prisma.FieldRef<"Fighter", 'DateTime'>
  readonly weight: Prisma.FieldRef<"Fighter", 'Float'>
  readonly clubId: Prisma.FieldRef<"Fighter", 'Int'>
}
    

// Custom InputTypes
/**
 * Fighter findUnique
 */
export type FighterFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * Filter, which Fighter to fetch.
   */
  where: Prisma.FighterWhereUniqueInput
}

/**
 * Fighter findUniqueOrThrow
 */
export type FighterFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * Filter, which Fighter to fetch.
   */
  where: Prisma.FighterWhereUniqueInput
}

/**
 * Fighter findFirst
 */
export type FighterFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * Filter, which Fighter to fetch.
   */
  where?: Prisma.FighterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fighters to fetch.
   */
  orderBy?: Prisma.FighterOrderByWithRelationInput | Prisma.FighterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Fighters.
   */
  cursor?: Prisma.FighterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fighters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fighters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fighters.
   */
  distinct?: Prisma.FighterScalarFieldEnum | Prisma.FighterScalarFieldEnum[]
}

/**
 * Fighter findFirstOrThrow
 */
export type FighterFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * Filter, which Fighter to fetch.
   */
  where?: Prisma.FighterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fighters to fetch.
   */
  orderBy?: Prisma.FighterOrderByWithRelationInput | Prisma.FighterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Fighters.
   */
  cursor?: Prisma.FighterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fighters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fighters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fighters.
   */
  distinct?: Prisma.FighterScalarFieldEnum | Prisma.FighterScalarFieldEnum[]
}

/**
 * Fighter findMany
 */
export type FighterFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * Filter, which Fighters to fetch.
   */
  where?: Prisma.FighterWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fighters to fetch.
   */
  orderBy?: Prisma.FighterOrderByWithRelationInput | Prisma.FighterOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Fighters.
   */
  cursor?: Prisma.FighterWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fighters from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fighters.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fighters.
   */
  distinct?: Prisma.FighterScalarFieldEnum | Prisma.FighterScalarFieldEnum[]
}

/**
 * Fighter create
 */
export type FighterCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * The data needed to create a Fighter.
   */
  data: Prisma.XOR<Prisma.FighterCreateInput, Prisma.FighterUncheckedCreateInput>
}

/**
 * Fighter createMany
 */
export type FighterCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Fighters.
   */
  data: Prisma.FighterCreateManyInput | Prisma.FighterCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Fighter createManyAndReturn
 */
export type FighterCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * The data used to create many Fighters.
   */
  data: Prisma.FighterCreateManyInput | Prisma.FighterCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Fighter update
 */
export type FighterUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * The data needed to update a Fighter.
   */
  data: Prisma.XOR<Prisma.FighterUpdateInput, Prisma.FighterUncheckedUpdateInput>
  /**
   * Choose, which Fighter to update.
   */
  where: Prisma.FighterWhereUniqueInput
}

/**
 * Fighter updateMany
 */
export type FighterUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Fighters.
   */
  data: Prisma.XOR<Prisma.FighterUpdateManyMutationInput, Prisma.FighterUncheckedUpdateManyInput>
  /**
   * Filter which Fighters to update
   */
  where?: Prisma.FighterWhereInput
  /**
   * Limit how many Fighters to update.
   */
  limit?: number
}

/**
 * Fighter updateManyAndReturn
 */
export type FighterUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * The data used to update Fighters.
   */
  data: Prisma.XOR<Prisma.FighterUpdateManyMutationInput, Prisma.FighterUncheckedUpdateManyInput>
  /**
   * Filter which Fighters to update
   */
  where?: Prisma.FighterWhereInput
  /**
   * Limit how many Fighters to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Fighter upsert
 */
export type FighterUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * The filter to search for the Fighter to update in case it exists.
   */
  where: Prisma.FighterWhereUniqueInput
  /**
   * In case the Fighter found by the `where` argument doesn't exist, create a new Fighter with this data.
   */
  create: Prisma.XOR<Prisma.FighterCreateInput, Prisma.FighterUncheckedCreateInput>
  /**
   * In case the Fighter was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FighterUpdateInput, Prisma.FighterUncheckedUpdateInput>
}

/**
 * Fighter delete
 */
export type FighterDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  /**
   * Filter which Fighter to delete.
   */
  where: Prisma.FighterWhereUniqueInput
}

/**
 * Fighter deleteMany
 */
export type FighterDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Fighters to delete
   */
  where?: Prisma.FighterWhereInput
  /**
   * Limit how many Fighters to delete.
   */
  limit?: number
}

/**
 * Fighter.category
 */
export type Fighter$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
}

/**
 * Fighter.tournament
 */
export type Fighter$tournamentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  where?: Prisma.TournamentWhereInput
}

/**
 * Fighter.club
 */
export type Fighter$clubArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  where?: Prisma.ClubWhereInput
}

/**
 * Fighter.matchesAsFighter1
 */
export type Fighter$matchesAsFighter1Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  where?: Prisma.MatchWhereInput
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  cursor?: Prisma.MatchWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Fighter.matchesAsFighter2
 */
export type Fighter$matchesAsFighter2Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  where?: Prisma.MatchWhereInput
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  cursor?: Prisma.MatchWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Fighter without action
 */
export type FighterDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
}
