
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Match` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Match
 * 
 */
export type MatchModel = runtime.Types.Result.DefaultSelection<Prisma.$MatchPayload>

export type AggregateMatch = {
  _count: MatchCountAggregateOutputType | null
  _avg: MatchAvgAggregateOutputType | null
  _sum: MatchSumAggregateOutputType | null
  _min: MatchMinAggregateOutputType | null
  _max: MatchMaxAggregateOutputType | null
}

export type MatchAvgAggregateOutputType = {
  round: number | null
  number: number | null
  fighter1Id: number | null
  fighter2Id: number | null
  winner: number | null
  tatami: number | null
  slotNumber: number | null
}

export type MatchSumAggregateOutputType = {
  round: number | null
  number: number | null
  fighter1Id: number | null
  fighter2Id: number | null
  winner: number | null
  tatami: number | null
  slotNumber: number | null
}

export type MatchMinAggregateOutputType = {
  id: string | null
  categoryId: string | null
  tournamentId: string | null
  round: number | null
  number: number | null
  fighter1Id: number | null
  fighter2Id: number | null
  winner: number | null
  tatami: number | null
  slotNumber: number | null
}

export type MatchMaxAggregateOutputType = {
  id: string | null
  categoryId: string | null
  tournamentId: string | null
  round: number | null
  number: number | null
  fighter1Id: number | null
  fighter2Id: number | null
  winner: number | null
  tatami: number | null
  slotNumber: number | null
}

export type MatchCountAggregateOutputType = {
  id: number
  categoryId: number
  tournamentId: number
  round: number
  number: number
  fighter1Id: number
  fighter2Id: number
  winner: number
  tatami: number
  slotNumber: number
  _all: number
}


export type MatchAvgAggregateInputType = {
  round?: true
  number?: true
  fighter1Id?: true
  fighter2Id?: true
  winner?: true
  tatami?: true
  slotNumber?: true
}

export type MatchSumAggregateInputType = {
  round?: true
  number?: true
  fighter1Id?: true
  fighter2Id?: true
  winner?: true
  tatami?: true
  slotNumber?: true
}

export type MatchMinAggregateInputType = {
  id?: true
  categoryId?: true
  tournamentId?: true
  round?: true
  number?: true
  fighter1Id?: true
  fighter2Id?: true
  winner?: true
  tatami?: true
  slotNumber?: true
}

export type MatchMaxAggregateInputType = {
  id?: true
  categoryId?: true
  tournamentId?: true
  round?: true
  number?: true
  fighter1Id?: true
  fighter2Id?: true
  winner?: true
  tatami?: true
  slotNumber?: true
}

export type MatchCountAggregateInputType = {
  id?: true
  categoryId?: true
  tournamentId?: true
  round?: true
  number?: true
  fighter1Id?: true
  fighter2Id?: true
  winner?: true
  tatami?: true
  slotNumber?: true
  _all?: true
}

export type MatchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Match to aggregate.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Matches
  **/
  _count?: true | MatchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MatchAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MatchSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MatchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MatchMaxAggregateInputType
}

export type GetMatchAggregateType<T extends MatchAggregateArgs> = {
      [P in keyof T & keyof AggregateMatch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMatch[P]>
    : Prisma.GetScalarType<T[P], AggregateMatch[P]>
}




export type MatchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchWhereInput
  orderBy?: Prisma.MatchOrderByWithAggregationInput | Prisma.MatchOrderByWithAggregationInput[]
  by: Prisma.MatchScalarFieldEnum[] | Prisma.MatchScalarFieldEnum
  having?: Prisma.MatchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MatchCountAggregateInputType | true
  _avg?: MatchAvgAggregateInputType
  _sum?: MatchSumAggregateInputType
  _min?: MatchMinAggregateInputType
  _max?: MatchMaxAggregateInputType
}

export type MatchGroupByOutputType = {
  id: string
  categoryId: string | null
  tournamentId: string | null
  round: number
  number: number
  fighter1Id: number | null
  fighter2Id: number | null
  winner: number | null
  tatami: number | null
  slotNumber: number | null
  _count: MatchCountAggregateOutputType | null
  _avg: MatchAvgAggregateOutputType | null
  _sum: MatchSumAggregateOutputType | null
  _min: MatchMinAggregateOutputType | null
  _max: MatchMaxAggregateOutputType | null
}

export type GetMatchGroupByPayload<T extends MatchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MatchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MatchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MatchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MatchGroupByOutputType[P]>
      }
    >
  >



export type MatchWhereInput = {
  AND?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  OR?: Prisma.MatchWhereInput[]
  NOT?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  id?: Prisma.StringFilter<"Match"> | string
  categoryId?: Prisma.StringNullableFilter<"Match"> | string | null
  tournamentId?: Prisma.StringNullableFilter<"Match"> | string | null
  round?: Prisma.IntFilter<"Match"> | number
  number?: Prisma.IntFilter<"Match"> | number
  fighter1Id?: Prisma.IntNullableFilter<"Match"> | number | null
  fighter2Id?: Prisma.IntNullableFilter<"Match"> | number | null
  winner?: Prisma.IntNullableFilter<"Match"> | number | null
  tatami?: Prisma.IntNullableFilter<"Match"> | number | null
  slotNumber?: Prisma.IntNullableFilter<"Match"> | number | null
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  fighter1?: Prisma.XOR<Prisma.FighterNullableScalarRelationFilter, Prisma.FighterWhereInput> | null
  fighter2?: Prisma.XOR<Prisma.FighterNullableScalarRelationFilter, Prisma.FighterWhereInput> | null
}

export type MatchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrderInput | Prisma.SortOrder
  fighter2Id?: Prisma.SortOrderInput | Prisma.SortOrder
  winner?: Prisma.SortOrderInput | Prisma.SortOrder
  tatami?: Prisma.SortOrderInput | Prisma.SortOrder
  slotNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.CategoryOrderByWithRelationInput
  tournament?: Prisma.TournamentOrderByWithRelationInput
  fighter1?: Prisma.FighterOrderByWithRelationInput
  fighter2?: Prisma.FighterOrderByWithRelationInput
}

export type MatchWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  OR?: Prisma.MatchWhereInput[]
  NOT?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  categoryId?: Prisma.StringNullableFilter<"Match"> | string | null
  tournamentId?: Prisma.StringNullableFilter<"Match"> | string | null
  round?: Prisma.IntFilter<"Match"> | number
  number?: Prisma.IntFilter<"Match"> | number
  fighter1Id?: Prisma.IntNullableFilter<"Match"> | number | null
  fighter2Id?: Prisma.IntNullableFilter<"Match"> | number | null
  winner?: Prisma.IntNullableFilter<"Match"> | number | null
  tatami?: Prisma.IntNullableFilter<"Match"> | number | null
  slotNumber?: Prisma.IntNullableFilter<"Match"> | number | null
  category?: Prisma.XOR<Prisma.CategoryNullableScalarRelationFilter, Prisma.CategoryWhereInput> | null
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
  fighter1?: Prisma.XOR<Prisma.FighterNullableScalarRelationFilter, Prisma.FighterWhereInput> | null
  fighter2?: Prisma.XOR<Prisma.FighterNullableScalarRelationFilter, Prisma.FighterWhereInput> | null
}, "id">

export type MatchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrderInput | Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrderInput | Prisma.SortOrder
  fighter2Id?: Prisma.SortOrderInput | Prisma.SortOrder
  winner?: Prisma.SortOrderInput | Prisma.SortOrder
  tatami?: Prisma.SortOrderInput | Prisma.SortOrder
  slotNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MatchCountOrderByAggregateInput
  _avg?: Prisma.MatchAvgOrderByAggregateInput
  _max?: Prisma.MatchMaxOrderByAggregateInput
  _min?: Prisma.MatchMinOrderByAggregateInput
  _sum?: Prisma.MatchSumOrderByAggregateInput
}

export type MatchScalarWhereWithAggregatesInput = {
  AND?: Prisma.MatchScalarWhereWithAggregatesInput | Prisma.MatchScalarWhereWithAggregatesInput[]
  OR?: Prisma.MatchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MatchScalarWhereWithAggregatesInput | Prisma.MatchScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Match"> | string
  categoryId?: Prisma.StringNullableWithAggregatesFilter<"Match"> | string | null
  tournamentId?: Prisma.StringNullableWithAggregatesFilter<"Match"> | string | null
  round?: Prisma.IntWithAggregatesFilter<"Match"> | number
  number?: Prisma.IntWithAggregatesFilter<"Match"> | number
  fighter1Id?: Prisma.IntNullableWithAggregatesFilter<"Match"> | number | null
  fighter2Id?: Prisma.IntNullableWithAggregatesFilter<"Match"> | number | null
  winner?: Prisma.IntNullableWithAggregatesFilter<"Match"> | number | null
  tatami?: Prisma.IntNullableWithAggregatesFilter<"Match"> | number | null
  slotNumber?: Prisma.IntNullableWithAggregatesFilter<"Match"> | number | null
}

export type MatchCreateInput = {
  id?: string
  round: number
  number: number
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
  category?: Prisma.CategoryCreateNestedOneWithoutMatchesInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutMatchesInput
  fighter1?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter1Input
  fighter2?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter2Input
}

export type MatchUncheckedCreateInput = {
  id?: string
  categoryId?: string | null
  tournamentId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  category?: Prisma.CategoryUpdateOneWithoutMatchesNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutMatchesNestedInput
  fighter1?: Prisma.FighterUpdateOneWithoutMatchesAsFighter1NestedInput
  fighter2?: Prisma.FighterUpdateOneWithoutMatchesAsFighter2NestedInput
}

export type MatchUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchCreateManyInput = {
  id?: string
  categoryId?: string | null
  tournamentId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchListRelationFilter = {
  every?: Prisma.MatchWhereInput
  some?: Prisma.MatchWhereInput
  none?: Prisma.MatchWhereInput
}

export type MatchOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MatchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrder
  fighter2Id?: Prisma.SortOrder
  winner?: Prisma.SortOrder
  tatami?: Prisma.SortOrder
  slotNumber?: Prisma.SortOrder
}

export type MatchAvgOrderByAggregateInput = {
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrder
  fighter2Id?: Prisma.SortOrder
  winner?: Prisma.SortOrder
  tatami?: Prisma.SortOrder
  slotNumber?: Prisma.SortOrder
}

export type MatchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrder
  fighter2Id?: Prisma.SortOrder
  winner?: Prisma.SortOrder
  tatami?: Prisma.SortOrder
  slotNumber?: Prisma.SortOrder
}

export type MatchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrder
  fighter2Id?: Prisma.SortOrder
  winner?: Prisma.SortOrder
  tatami?: Prisma.SortOrder
  slotNumber?: Prisma.SortOrder
}

export type MatchSumOrderByAggregateInput = {
  round?: Prisma.SortOrder
  number?: Prisma.SortOrder
  fighter1Id?: Prisma.SortOrder
  fighter2Id?: Prisma.SortOrder
  winner?: Prisma.SortOrder
  tatami?: Prisma.SortOrder
  slotNumber?: Prisma.SortOrder
}

export type MatchCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutTournamentInput, Prisma.MatchUncheckedCreateWithoutTournamentInput> | Prisma.MatchCreateWithoutTournamentInput[] | Prisma.MatchUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutTournamentInput | Prisma.MatchCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.MatchCreateManyTournamentInputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutTournamentInput, Prisma.MatchUncheckedCreateWithoutTournamentInput> | Prisma.MatchCreateWithoutTournamentInput[] | Prisma.MatchUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutTournamentInput | Prisma.MatchCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.MatchCreateManyTournamentInputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutTournamentInput, Prisma.MatchUncheckedCreateWithoutTournamentInput> | Prisma.MatchCreateWithoutTournamentInput[] | Prisma.MatchUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutTournamentInput | Prisma.MatchCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutTournamentInput | Prisma.MatchUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.MatchCreateManyTournamentInputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutTournamentInput | Prisma.MatchUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutTournamentInput | Prisma.MatchUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutTournamentInput, Prisma.MatchUncheckedCreateWithoutTournamentInput> | Prisma.MatchCreateWithoutTournamentInput[] | Prisma.MatchUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutTournamentInput | Prisma.MatchCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutTournamentInput | Prisma.MatchUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.MatchCreateManyTournamentInputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutTournamentInput | Prisma.MatchUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutTournamentInput | Prisma.MatchUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutCategoryInput, Prisma.MatchUncheckedCreateWithoutCategoryInput> | Prisma.MatchCreateWithoutCategoryInput[] | Prisma.MatchUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutCategoryInput | Prisma.MatchCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.MatchCreateManyCategoryInputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutCategoryInput, Prisma.MatchUncheckedCreateWithoutCategoryInput> | Prisma.MatchCreateWithoutCategoryInput[] | Prisma.MatchUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutCategoryInput | Prisma.MatchCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.MatchCreateManyCategoryInputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutCategoryInput, Prisma.MatchUncheckedCreateWithoutCategoryInput> | Prisma.MatchCreateWithoutCategoryInput[] | Prisma.MatchUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutCategoryInput | Prisma.MatchCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutCategoryInput | Prisma.MatchUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.MatchCreateManyCategoryInputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutCategoryInput | Prisma.MatchUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutCategoryInput | Prisma.MatchUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutCategoryInput, Prisma.MatchUncheckedCreateWithoutCategoryInput> | Prisma.MatchCreateWithoutCategoryInput[] | Prisma.MatchUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutCategoryInput | Prisma.MatchCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutCategoryInput | Prisma.MatchUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.MatchCreateManyCategoryInputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutCategoryInput | Prisma.MatchUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutCategoryInput | Prisma.MatchUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type MatchCreateNestedManyWithoutFighter1Input = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter1Input, Prisma.MatchUncheckedCreateWithoutFighter1Input> | Prisma.MatchCreateWithoutFighter1Input[] | Prisma.MatchUncheckedCreateWithoutFighter1Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter1Input | Prisma.MatchCreateOrConnectWithoutFighter1Input[]
  createMany?: Prisma.MatchCreateManyFighter1InputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchCreateNestedManyWithoutFighter2Input = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter2Input, Prisma.MatchUncheckedCreateWithoutFighter2Input> | Prisma.MatchCreateWithoutFighter2Input[] | Prisma.MatchUncheckedCreateWithoutFighter2Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter2Input | Prisma.MatchCreateOrConnectWithoutFighter2Input[]
  createMany?: Prisma.MatchCreateManyFighter2InputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUncheckedCreateNestedManyWithoutFighter1Input = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter1Input, Prisma.MatchUncheckedCreateWithoutFighter1Input> | Prisma.MatchCreateWithoutFighter1Input[] | Prisma.MatchUncheckedCreateWithoutFighter1Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter1Input | Prisma.MatchCreateOrConnectWithoutFighter1Input[]
  createMany?: Prisma.MatchCreateManyFighter1InputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUncheckedCreateNestedManyWithoutFighter2Input = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter2Input, Prisma.MatchUncheckedCreateWithoutFighter2Input> | Prisma.MatchCreateWithoutFighter2Input[] | Prisma.MatchUncheckedCreateWithoutFighter2Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter2Input | Prisma.MatchCreateOrConnectWithoutFighter2Input[]
  createMany?: Prisma.MatchCreateManyFighter2InputEnvelope
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
}

export type MatchUpdateManyWithoutFighter1NestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter1Input, Prisma.MatchUncheckedCreateWithoutFighter1Input> | Prisma.MatchCreateWithoutFighter1Input[] | Prisma.MatchUncheckedCreateWithoutFighter1Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter1Input | Prisma.MatchCreateOrConnectWithoutFighter1Input[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutFighter1Input | Prisma.MatchUpsertWithWhereUniqueWithoutFighter1Input[]
  createMany?: Prisma.MatchCreateManyFighter1InputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutFighter1Input | Prisma.MatchUpdateWithWhereUniqueWithoutFighter1Input[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutFighter1Input | Prisma.MatchUpdateManyWithWhereWithoutFighter1Input[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchUpdateManyWithoutFighter2NestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter2Input, Prisma.MatchUncheckedCreateWithoutFighter2Input> | Prisma.MatchCreateWithoutFighter2Input[] | Prisma.MatchUncheckedCreateWithoutFighter2Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter2Input | Prisma.MatchCreateOrConnectWithoutFighter2Input[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutFighter2Input | Prisma.MatchUpsertWithWhereUniqueWithoutFighter2Input[]
  createMany?: Prisma.MatchCreateManyFighter2InputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutFighter2Input | Prisma.MatchUpdateWithWhereUniqueWithoutFighter2Input[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutFighter2Input | Prisma.MatchUpdateManyWithWhereWithoutFighter2Input[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchUncheckedUpdateManyWithoutFighter1NestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter1Input, Prisma.MatchUncheckedCreateWithoutFighter1Input> | Prisma.MatchCreateWithoutFighter1Input[] | Prisma.MatchUncheckedCreateWithoutFighter1Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter1Input | Prisma.MatchCreateOrConnectWithoutFighter1Input[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutFighter1Input | Prisma.MatchUpsertWithWhereUniqueWithoutFighter1Input[]
  createMany?: Prisma.MatchCreateManyFighter1InputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutFighter1Input | Prisma.MatchUpdateWithWhereUniqueWithoutFighter1Input[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutFighter1Input | Prisma.MatchUpdateManyWithWhereWithoutFighter1Input[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchUncheckedUpdateManyWithoutFighter2NestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutFighter2Input, Prisma.MatchUncheckedCreateWithoutFighter2Input> | Prisma.MatchCreateWithoutFighter2Input[] | Prisma.MatchUncheckedCreateWithoutFighter2Input[]
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutFighter2Input | Prisma.MatchCreateOrConnectWithoutFighter2Input[]
  upsert?: Prisma.MatchUpsertWithWhereUniqueWithoutFighter2Input | Prisma.MatchUpsertWithWhereUniqueWithoutFighter2Input[]
  createMany?: Prisma.MatchCreateManyFighter2InputEnvelope
  set?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  disconnect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  delete?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  connect?: Prisma.MatchWhereUniqueInput | Prisma.MatchWhereUniqueInput[]
  update?: Prisma.MatchUpdateWithWhereUniqueWithoutFighter2Input | Prisma.MatchUpdateWithWhereUniqueWithoutFighter2Input[]
  updateMany?: Prisma.MatchUpdateManyWithWhereWithoutFighter2Input | Prisma.MatchUpdateManyWithWhereWithoutFighter2Input[]
  deleteMany?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
}

export type MatchCreateWithoutTournamentInput = {
  id?: string
  round: number
  number: number
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
  category?: Prisma.CategoryCreateNestedOneWithoutMatchesInput
  fighter1?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter1Input
  fighter2?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter2Input
}

export type MatchUncheckedCreateWithoutTournamentInput = {
  id?: string
  categoryId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchCreateOrConnectWithoutTournamentInput = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutTournamentInput, Prisma.MatchUncheckedCreateWithoutTournamentInput>
}

export type MatchCreateManyTournamentInputEnvelope = {
  data: Prisma.MatchCreateManyTournamentInput | Prisma.MatchCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type MatchUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.MatchWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchUpdateWithoutTournamentInput, Prisma.MatchUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.MatchCreateWithoutTournamentInput, Prisma.MatchUncheckedCreateWithoutTournamentInput>
}

export type MatchUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.MatchWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutTournamentInput, Prisma.MatchUncheckedUpdateWithoutTournamentInput>
}

export type MatchUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.MatchScalarWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyWithoutTournamentInput>
}

export type MatchScalarWhereInput = {
  AND?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
  OR?: Prisma.MatchScalarWhereInput[]
  NOT?: Prisma.MatchScalarWhereInput | Prisma.MatchScalarWhereInput[]
  id?: Prisma.StringFilter<"Match"> | string
  categoryId?: Prisma.StringNullableFilter<"Match"> | string | null
  tournamentId?: Prisma.StringNullableFilter<"Match"> | string | null
  round?: Prisma.IntFilter<"Match"> | number
  number?: Prisma.IntFilter<"Match"> | number
  fighter1Id?: Prisma.IntNullableFilter<"Match"> | number | null
  fighter2Id?: Prisma.IntNullableFilter<"Match"> | number | null
  winner?: Prisma.IntNullableFilter<"Match"> | number | null
  tatami?: Prisma.IntNullableFilter<"Match"> | number | null
  slotNumber?: Prisma.IntNullableFilter<"Match"> | number | null
}

export type MatchCreateWithoutCategoryInput = {
  id?: string
  round: number
  number: number
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
  tournament?: Prisma.TournamentCreateNestedOneWithoutMatchesInput
  fighter1?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter1Input
  fighter2?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter2Input
}

export type MatchUncheckedCreateWithoutCategoryInput = {
  id?: string
  tournamentId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchCreateOrConnectWithoutCategoryInput = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutCategoryInput, Prisma.MatchUncheckedCreateWithoutCategoryInput>
}

export type MatchCreateManyCategoryInputEnvelope = {
  data: Prisma.MatchCreateManyCategoryInput | Prisma.MatchCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type MatchUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.MatchWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchUpdateWithoutCategoryInput, Prisma.MatchUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.MatchCreateWithoutCategoryInput, Prisma.MatchUncheckedCreateWithoutCategoryInput>
}

export type MatchUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.MatchWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutCategoryInput, Prisma.MatchUncheckedUpdateWithoutCategoryInput>
}

export type MatchUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.MatchScalarWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyWithoutCategoryInput>
}

export type MatchCreateWithoutFighter1Input = {
  id?: string
  round: number
  number: number
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
  category?: Prisma.CategoryCreateNestedOneWithoutMatchesInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutMatchesInput
  fighter2?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter2Input
}

export type MatchUncheckedCreateWithoutFighter1Input = {
  id?: string
  categoryId?: string | null
  tournamentId?: string | null
  round: number
  number: number
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchCreateOrConnectWithoutFighter1Input = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutFighter1Input, Prisma.MatchUncheckedCreateWithoutFighter1Input>
}

export type MatchCreateManyFighter1InputEnvelope = {
  data: Prisma.MatchCreateManyFighter1Input | Prisma.MatchCreateManyFighter1Input[]
  skipDuplicates?: boolean
}

export type MatchCreateWithoutFighter2Input = {
  id?: string
  round: number
  number: number
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
  category?: Prisma.CategoryCreateNestedOneWithoutMatchesInput
  tournament?: Prisma.TournamentCreateNestedOneWithoutMatchesInput
  fighter1?: Prisma.FighterCreateNestedOneWithoutMatchesAsFighter1Input
}

export type MatchUncheckedCreateWithoutFighter2Input = {
  id?: string
  categoryId?: string | null
  tournamentId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchCreateOrConnectWithoutFighter2Input = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutFighter2Input, Prisma.MatchUncheckedCreateWithoutFighter2Input>
}

export type MatchCreateManyFighter2InputEnvelope = {
  data: Prisma.MatchCreateManyFighter2Input | Prisma.MatchCreateManyFighter2Input[]
  skipDuplicates?: boolean
}

export type MatchUpsertWithWhereUniqueWithoutFighter1Input = {
  where: Prisma.MatchWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchUpdateWithoutFighter1Input, Prisma.MatchUncheckedUpdateWithoutFighter1Input>
  create: Prisma.XOR<Prisma.MatchCreateWithoutFighter1Input, Prisma.MatchUncheckedCreateWithoutFighter1Input>
}

export type MatchUpdateWithWhereUniqueWithoutFighter1Input = {
  where: Prisma.MatchWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutFighter1Input, Prisma.MatchUncheckedUpdateWithoutFighter1Input>
}

export type MatchUpdateManyWithWhereWithoutFighter1Input = {
  where: Prisma.MatchScalarWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyWithoutFighter1Input>
}

export type MatchUpsertWithWhereUniqueWithoutFighter2Input = {
  where: Prisma.MatchWhereUniqueInput
  update: Prisma.XOR<Prisma.MatchUpdateWithoutFighter2Input, Prisma.MatchUncheckedUpdateWithoutFighter2Input>
  create: Prisma.XOR<Prisma.MatchCreateWithoutFighter2Input, Prisma.MatchUncheckedCreateWithoutFighter2Input>
}

export type MatchUpdateWithWhereUniqueWithoutFighter2Input = {
  where: Prisma.MatchWhereUniqueInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutFighter2Input, Prisma.MatchUncheckedUpdateWithoutFighter2Input>
}

export type MatchUpdateManyWithWhereWithoutFighter2Input = {
  where: Prisma.MatchScalarWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyWithoutFighter2Input>
}

export type MatchCreateManyTournamentInput = {
  id?: string
  categoryId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  category?: Prisma.CategoryUpdateOneWithoutMatchesNestedInput
  fighter1?: Prisma.FighterUpdateOneWithoutMatchesAsFighter1NestedInput
  fighter2?: Prisma.FighterUpdateOneWithoutMatchesAsFighter2NestedInput
}

export type MatchUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchCreateManyCategoryInput = {
  id?: string
  tournamentId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tournament?: Prisma.TournamentUpdateOneWithoutMatchesNestedInput
  fighter1?: Prisma.FighterUpdateOneWithoutMatchesAsFighter1NestedInput
  fighter2?: Prisma.FighterUpdateOneWithoutMatchesAsFighter2NestedInput
}

export type MatchUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchCreateManyFighter1Input = {
  id?: string
  categoryId?: string | null
  tournamentId?: string | null
  round: number
  number: number
  fighter2Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchCreateManyFighter2Input = {
  id?: string
  categoryId?: string | null
  tournamentId?: string | null
  round: number
  number: number
  fighter1Id?: number | null
  winner?: number | null
  tatami?: number | null
  slotNumber?: number | null
}

export type MatchUpdateWithoutFighter1Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  category?: Prisma.CategoryUpdateOneWithoutMatchesNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutMatchesNestedInput
  fighter2?: Prisma.FighterUpdateOneWithoutMatchesAsFighter2NestedInput
}

export type MatchUncheckedUpdateWithoutFighter1Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchUncheckedUpdateManyWithoutFighter1Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter2Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchUpdateWithoutFighter2Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  category?: Prisma.CategoryUpdateOneWithoutMatchesNestedInput
  tournament?: Prisma.TournamentUpdateOneWithoutMatchesNestedInput
  fighter1?: Prisma.FighterUpdateOneWithoutMatchesAsFighter1NestedInput
}

export type MatchUncheckedUpdateWithoutFighter2Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type MatchUncheckedUpdateManyWithoutFighter2Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  categoryId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  round?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  fighter1Id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  winner?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  tatami?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  slotNumber?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type MatchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  round?: boolean
  number?: boolean
  fighter1Id?: boolean
  fighter2Id?: boolean
  winner?: boolean
  tatami?: boolean
  slotNumber?: boolean
  category?: boolean | Prisma.Match$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Match$tournamentArgs<ExtArgs>
  fighter1?: boolean | Prisma.Match$fighter1Args<ExtArgs>
  fighter2?: boolean | Prisma.Match$fighter2Args<ExtArgs>
}, ExtArgs["result"]["match"]>

export type MatchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  round?: boolean
  number?: boolean
  fighter1Id?: boolean
  fighter2Id?: boolean
  winner?: boolean
  tatami?: boolean
  slotNumber?: boolean
  category?: boolean | Prisma.Match$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Match$tournamentArgs<ExtArgs>
  fighter1?: boolean | Prisma.Match$fighter1Args<ExtArgs>
  fighter2?: boolean | Prisma.Match$fighter2Args<ExtArgs>
}, ExtArgs["result"]["match"]>

export type MatchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  round?: boolean
  number?: boolean
  fighter1Id?: boolean
  fighter2Id?: boolean
  winner?: boolean
  tatami?: boolean
  slotNumber?: boolean
  category?: boolean | Prisma.Match$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Match$tournamentArgs<ExtArgs>
  fighter1?: boolean | Prisma.Match$fighter1Args<ExtArgs>
  fighter2?: boolean | Prisma.Match$fighter2Args<ExtArgs>
}, ExtArgs["result"]["match"]>

export type MatchSelectScalar = {
  id?: boolean
  categoryId?: boolean
  tournamentId?: boolean
  round?: boolean
  number?: boolean
  fighter1Id?: boolean
  fighter2Id?: boolean
  winner?: boolean
  tatami?: boolean
  slotNumber?: boolean
}

export type MatchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "categoryId" | "tournamentId" | "round" | "number" | "fighter1Id" | "fighter2Id" | "winner" | "tatami" | "slotNumber", ExtArgs["result"]["match"]>
export type MatchInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Match$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Match$tournamentArgs<ExtArgs>
  fighter1?: boolean | Prisma.Match$fighter1Args<ExtArgs>
  fighter2?: boolean | Prisma.Match$fighter2Args<ExtArgs>
}
export type MatchIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Match$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Match$tournamentArgs<ExtArgs>
  fighter1?: boolean | Prisma.Match$fighter1Args<ExtArgs>
  fighter2?: boolean | Prisma.Match$fighter2Args<ExtArgs>
}
export type MatchIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.Match$categoryArgs<ExtArgs>
  tournament?: boolean | Prisma.Match$tournamentArgs<ExtArgs>
  fighter1?: boolean | Prisma.Match$fighter1Args<ExtArgs>
  fighter2?: boolean | Prisma.Match$fighter2Args<ExtArgs>
}

export type $MatchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Match"
  objects: {
    category: Prisma.$CategoryPayload<ExtArgs> | null
    tournament: Prisma.$TournamentPayload<ExtArgs> | null
    fighter1: Prisma.$FighterPayload<ExtArgs> | null
    fighter2: Prisma.$FighterPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    categoryId: string | null
    tournamentId: string | null
    round: number
    number: number
    fighter1Id: number | null
    fighter2Id: number | null
    winner: number | null
    tatami: number | null
    slotNumber: number | null
  }, ExtArgs["result"]["match"]>
  composites: {}
}

export type MatchGetPayload<S extends boolean | null | undefined | MatchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MatchPayload, S>

export type MatchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MatchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MatchCountAggregateInputType | true
  }

export interface MatchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Match'], meta: { name: 'Match' } }
  /**
   * Find zero or one Match that matches the filter.
   * @param {MatchFindUniqueArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MatchFindUniqueArgs>(args: Prisma.SelectSubset<T, MatchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Match that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MatchFindUniqueOrThrowArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MatchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MatchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Match that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchFindFirstArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MatchFindFirstArgs>(args?: Prisma.SelectSubset<T, MatchFindFirstArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Match that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchFindFirstOrThrowArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MatchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MatchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Matches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Matches
   * const matches = await prisma.match.findMany()
   * 
   * // Get first 10 Matches
   * const matches = await prisma.match.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const matchWithIdOnly = await prisma.match.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MatchFindManyArgs>(args?: Prisma.SelectSubset<T, MatchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Match.
   * @param {MatchCreateArgs} args - Arguments to create a Match.
   * @example
   * // Create one Match
   * const Match = await prisma.match.create({
   *   data: {
   *     // ... data to create a Match
   *   }
   * })
   * 
   */
  create<T extends MatchCreateArgs>(args: Prisma.SelectSubset<T, MatchCreateArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Matches.
   * @param {MatchCreateManyArgs} args - Arguments to create many Matches.
   * @example
   * // Create many Matches
   * const match = await prisma.match.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MatchCreateManyArgs>(args?: Prisma.SelectSubset<T, MatchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Matches and returns the data saved in the database.
   * @param {MatchCreateManyAndReturnArgs} args - Arguments to create many Matches.
   * @example
   * // Create many Matches
   * const match = await prisma.match.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Matches and only return the `id`
   * const matchWithIdOnly = await prisma.match.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MatchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MatchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Match.
   * @param {MatchDeleteArgs} args - Arguments to delete one Match.
   * @example
   * // Delete one Match
   * const Match = await prisma.match.delete({
   *   where: {
   *     // ... filter to delete one Match
   *   }
   * })
   * 
   */
  delete<T extends MatchDeleteArgs>(args: Prisma.SelectSubset<T, MatchDeleteArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Match.
   * @param {MatchUpdateArgs} args - Arguments to update one Match.
   * @example
   * // Update one Match
   * const match = await prisma.match.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MatchUpdateArgs>(args: Prisma.SelectSubset<T, MatchUpdateArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Matches.
   * @param {MatchDeleteManyArgs} args - Arguments to filter Matches to delete.
   * @example
   * // Delete a few Matches
   * const { count } = await prisma.match.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MatchDeleteManyArgs>(args?: Prisma.SelectSubset<T, MatchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Matches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Matches
   * const match = await prisma.match.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MatchUpdateManyArgs>(args: Prisma.SelectSubset<T, MatchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Matches and returns the data updated in the database.
   * @param {MatchUpdateManyAndReturnArgs} args - Arguments to update many Matches.
   * @example
   * // Update many Matches
   * const match = await prisma.match.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Matches and only return the `id`
   * const matchWithIdOnly = await prisma.match.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MatchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MatchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Match.
   * @param {MatchUpsertArgs} args - Arguments to update or create a Match.
   * @example
   * // Update or create a Match
   * const match = await prisma.match.upsert({
   *   create: {
   *     // ... data to create a Match
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Match we want to update
   *   }
   * })
   */
  upsert<T extends MatchUpsertArgs>(args: Prisma.SelectSubset<T, MatchUpsertArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Matches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchCountArgs} args - Arguments to filter Matches to count.
   * @example
   * // Count the number of Matches
   * const count = await prisma.match.count({
   *   where: {
   *     // ... the filter for the Matches we want to count
   *   }
   * })
  **/
  count<T extends MatchCountArgs>(
    args?: Prisma.Subset<T, MatchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MatchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Match.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MatchAggregateArgs>(args: Prisma.Subset<T, MatchAggregateArgs>): Prisma.PrismaPromise<GetMatchAggregateType<T>>

  /**
   * Group by Match.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MatchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MatchGroupByArgs['orderBy'] }
      : { orderBy?: MatchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MatchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMatchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Match model
 */
readonly fields: MatchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Match.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MatchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.Match$categoryArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$categoryArgs<ExtArgs>>): Prisma.Prisma__CategoryClient<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  tournament<T extends Prisma.Match$tournamentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$tournamentArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  fighter1<T extends Prisma.Match$fighter1Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$fighter1Args<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  fighter2<T extends Prisma.Match$fighter2Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$fighter2Args<ExtArgs>>): Prisma.Prisma__FighterClient<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Match model
 */
export interface MatchFieldRefs {
  readonly id: Prisma.FieldRef<"Match", 'String'>
  readonly categoryId: Prisma.FieldRef<"Match", 'String'>
  readonly tournamentId: Prisma.FieldRef<"Match", 'String'>
  readonly round: Prisma.FieldRef<"Match", 'Int'>
  readonly number: Prisma.FieldRef<"Match", 'Int'>
  readonly fighter1Id: Prisma.FieldRef<"Match", 'Int'>
  readonly fighter2Id: Prisma.FieldRef<"Match", 'Int'>
  readonly winner: Prisma.FieldRef<"Match", 'Int'>
  readonly tatami: Prisma.FieldRef<"Match", 'Int'>
  readonly slotNumber: Prisma.FieldRef<"Match", 'Int'>
}
    

// Custom InputTypes
/**
 * Match findUnique
 */
export type MatchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match findUniqueOrThrow
 */
export type MatchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match findFirst
 */
export type MatchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Matches.
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Matches.
   */
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Match findFirstOrThrow
 */
export type MatchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Matches.
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Matches.
   */
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Match findMany
 */
export type MatchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Matches to fetch.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Matches.
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Matches.
   */
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Match create
 */
export type MatchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * The data needed to create a Match.
   */
  data: Prisma.XOR<Prisma.MatchCreateInput, Prisma.MatchUncheckedCreateInput>
}

/**
 * Match createMany
 */
export type MatchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Matches.
   */
  data: Prisma.MatchCreateManyInput | Prisma.MatchCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Match createManyAndReturn
 */
export type MatchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * The data used to create many Matches.
   */
  data: Prisma.MatchCreateManyInput | Prisma.MatchCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Match update
 */
export type MatchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * The data needed to update a Match.
   */
  data: Prisma.XOR<Prisma.MatchUpdateInput, Prisma.MatchUncheckedUpdateInput>
  /**
   * Choose, which Match to update.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match updateMany
 */
export type MatchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Matches.
   */
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyInput>
  /**
   * Filter which Matches to update
   */
  where?: Prisma.MatchWhereInput
  /**
   * Limit how many Matches to update.
   */
  limit?: number
}

/**
 * Match updateManyAndReturn
 */
export type MatchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * The data used to update Matches.
   */
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyInput>
  /**
   * Filter which Matches to update
   */
  where?: Prisma.MatchWhereInput
  /**
   * Limit how many Matches to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Match upsert
 */
export type MatchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * The filter to search for the Match to update in case it exists.
   */
  where: Prisma.MatchWhereUniqueInput
  /**
   * In case the Match found by the `where` argument doesn't exist, create a new Match with this data.
   */
  create: Prisma.XOR<Prisma.MatchCreateInput, Prisma.MatchUncheckedCreateInput>
  /**
   * In case the Match was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MatchUpdateInput, Prisma.MatchUncheckedUpdateInput>
}

/**
 * Match delete
 */
export type MatchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter which Match to delete.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match deleteMany
 */
export type MatchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Matches to delete
   */
  where?: Prisma.MatchWhereInput
  /**
   * Limit how many Matches to delete.
   */
  limit?: number
}

/**
 * Match.category
 */
export type Match$categoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
}

/**
 * Match.tournament
 */
export type Match$tournamentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  where?: Prisma.TournamentWhereInput
}

/**
 * Match.fighter1
 */
export type Match$fighter1Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  where?: Prisma.FighterWhereInput
}

/**
 * Match.fighter2
 */
export type Match$fighter2Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  where?: Prisma.FighterWhereInput
}

/**
 * Match without action
 */
export type MatchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
}
