
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TimeRow` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TimeRow
 * 
 */
export type TimeRowModel = runtime.Types.Result.DefaultSelection<Prisma.$TimeRowPayload>

export type AggregateTimeRow = {
  _count: TimeRowCountAggregateOutputType | null
  _min: TimeRowMinAggregateOutputType | null
  _max: TimeRowMaxAggregateOutputType | null
}

export type TimeRowMinAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  date: Date | null
  timeline: string | null
  event: string | null
}

export type TimeRowMaxAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  date: Date | null
  timeline: string | null
  event: string | null
}

export type TimeRowCountAggregateOutputType = {
  id: number
  tournamentId: number
  date: number
  timeline: number
  event: number
  _all: number
}


export type TimeRowMinAggregateInputType = {
  id?: true
  tournamentId?: true
  date?: true
  timeline?: true
  event?: true
}

export type TimeRowMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  date?: true
  timeline?: true
  event?: true
}

export type TimeRowCountAggregateInputType = {
  id?: true
  tournamentId?: true
  date?: true
  timeline?: true
  event?: true
  _all?: true
}

export type TimeRowAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeRow to aggregate.
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeRows to fetch.
   */
  orderBy?: Prisma.TimeRowOrderByWithRelationInput | Prisma.TimeRowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TimeRowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeRows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeRows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TimeRows
  **/
  _count?: true | TimeRowCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimeRowMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimeRowMaxAggregateInputType
}

export type GetTimeRowAggregateType<T extends TimeRowAggregateArgs> = {
      [P in keyof T & keyof AggregateTimeRow]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTimeRow[P]>
    : Prisma.GetScalarType<T[P], AggregateTimeRow[P]>
}




export type TimeRowGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeRowWhereInput
  orderBy?: Prisma.TimeRowOrderByWithAggregationInput | Prisma.TimeRowOrderByWithAggregationInput[]
  by: Prisma.TimeRowScalarFieldEnum[] | Prisma.TimeRowScalarFieldEnum
  having?: Prisma.TimeRowScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimeRowCountAggregateInputType | true
  _min?: TimeRowMinAggregateInputType
  _max?: TimeRowMaxAggregateInputType
}

export type TimeRowGroupByOutputType = {
  id: string
  tournamentId: string | null
  date: Date
  timeline: string
  event: string
  _count: TimeRowCountAggregateOutputType | null
  _min: TimeRowMinAggregateOutputType | null
  _max: TimeRowMaxAggregateOutputType | null
}

export type GetTimeRowGroupByPayload<T extends TimeRowGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimeRowGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimeRowGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimeRowGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimeRowGroupByOutputType[P]>
      }
    >
  >



export type TimeRowWhereInput = {
  AND?: Prisma.TimeRowWhereInput | Prisma.TimeRowWhereInput[]
  OR?: Prisma.TimeRowWhereInput[]
  NOT?: Prisma.TimeRowWhereInput | Prisma.TimeRowWhereInput[]
  id?: Prisma.StringFilter<"TimeRow"> | string
  tournamentId?: Prisma.StringNullableFilter<"TimeRow"> | string | null
  date?: Prisma.DateTimeFilter<"TimeRow"> | Date | string
  timeline?: Prisma.StringFilter<"TimeRow"> | string
  event?: Prisma.StringFilter<"TimeRow"> | string
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
}

export type TimeRowOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  event?: Prisma.SortOrder
  tournament?: Prisma.TournamentOrderByWithRelationInput
}

export type TimeRowWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TimeRowWhereInput | Prisma.TimeRowWhereInput[]
  OR?: Prisma.TimeRowWhereInput[]
  NOT?: Prisma.TimeRowWhereInput | Prisma.TimeRowWhereInput[]
  tournamentId?: Prisma.StringNullableFilter<"TimeRow"> | string | null
  date?: Prisma.DateTimeFilter<"TimeRow"> | Date | string
  timeline?: Prisma.StringFilter<"TimeRow"> | string
  event?: Prisma.StringFilter<"TimeRow"> | string
  tournament?: Prisma.XOR<Prisma.TournamentNullableScalarRelationFilter, Prisma.TournamentWhereInput> | null
}, "id">

export type TimeRowOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  event?: Prisma.SortOrder
  _count?: Prisma.TimeRowCountOrderByAggregateInput
  _max?: Prisma.TimeRowMaxOrderByAggregateInput
  _min?: Prisma.TimeRowMinOrderByAggregateInput
}

export type TimeRowScalarWhereWithAggregatesInput = {
  AND?: Prisma.TimeRowScalarWhereWithAggregatesInput | Prisma.TimeRowScalarWhereWithAggregatesInput[]
  OR?: Prisma.TimeRowScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TimeRowScalarWhereWithAggregatesInput | Prisma.TimeRowScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TimeRow"> | string
  tournamentId?: Prisma.StringNullableWithAggregatesFilter<"TimeRow"> | string | null
  date?: Prisma.DateTimeWithAggregatesFilter<"TimeRow"> | Date | string
  timeline?: Prisma.StringWithAggregatesFilter<"TimeRow"> | string
  event?: Prisma.StringWithAggregatesFilter<"TimeRow"> | string
}

export type TimeRowCreateInput = {
  id?: string
  date: Date | string
  timeline: string
  event: string
  tournament?: Prisma.TournamentCreateNestedOneWithoutTimetableInput
}

export type TimeRowUncheckedCreateInput = {
  id?: string
  tournamentId?: string | null
  date: Date | string
  timeline: string
  event: string
}

export type TimeRowUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
  tournament?: Prisma.TournamentUpdateOneWithoutTimetableNestedInput
}

export type TimeRowUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TimeRowCreateManyInput = {
  id?: string
  tournamentId?: string | null
  date: Date | string
  timeline: string
  event: string
}

export type TimeRowUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TimeRowUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TimeRowListRelationFilter = {
  every?: Prisma.TimeRowWhereInput
  some?: Prisma.TimeRowWhereInput
  none?: Prisma.TimeRowWhereInput
}

export type TimeRowOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TimeRowCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  event?: Prisma.SortOrder
}

export type TimeRowMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  event?: Prisma.SortOrder
}

export type TimeRowMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  event?: Prisma.SortOrder
}

export type TimeRowCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TimeRowCreateWithoutTournamentInput, Prisma.TimeRowUncheckedCreateWithoutTournamentInput> | Prisma.TimeRowCreateWithoutTournamentInput[] | Prisma.TimeRowUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TimeRowCreateOrConnectWithoutTournamentInput | Prisma.TimeRowCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TimeRowCreateManyTournamentInputEnvelope
  connect?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
}

export type TimeRowUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TimeRowCreateWithoutTournamentInput, Prisma.TimeRowUncheckedCreateWithoutTournamentInput> | Prisma.TimeRowCreateWithoutTournamentInput[] | Prisma.TimeRowUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TimeRowCreateOrConnectWithoutTournamentInput | Prisma.TimeRowCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TimeRowCreateManyTournamentInputEnvelope
  connect?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
}

export type TimeRowUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TimeRowCreateWithoutTournamentInput, Prisma.TimeRowUncheckedCreateWithoutTournamentInput> | Prisma.TimeRowCreateWithoutTournamentInput[] | Prisma.TimeRowUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TimeRowCreateOrConnectWithoutTournamentInput | Prisma.TimeRowCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TimeRowUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TimeRowUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TimeRowCreateManyTournamentInputEnvelope
  set?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  disconnect?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  delete?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  connect?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  update?: Prisma.TimeRowUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TimeRowUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TimeRowUpdateManyWithWhereWithoutTournamentInput | Prisma.TimeRowUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TimeRowScalarWhereInput | Prisma.TimeRowScalarWhereInput[]
}

export type TimeRowUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TimeRowCreateWithoutTournamentInput, Prisma.TimeRowUncheckedCreateWithoutTournamentInput> | Prisma.TimeRowCreateWithoutTournamentInput[] | Prisma.TimeRowUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TimeRowCreateOrConnectWithoutTournamentInput | Prisma.TimeRowCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TimeRowUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TimeRowUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TimeRowCreateManyTournamentInputEnvelope
  set?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  disconnect?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  delete?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  connect?: Prisma.TimeRowWhereUniqueInput | Prisma.TimeRowWhereUniqueInput[]
  update?: Prisma.TimeRowUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TimeRowUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TimeRowUpdateManyWithWhereWithoutTournamentInput | Prisma.TimeRowUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TimeRowScalarWhereInput | Prisma.TimeRowScalarWhereInput[]
}

export type TimeRowCreateWithoutTournamentInput = {
  id?: string
  date: Date | string
  timeline: string
  event: string
}

export type TimeRowUncheckedCreateWithoutTournamentInput = {
  id?: string
  date: Date | string
  timeline: string
  event: string
}

export type TimeRowCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TimeRowWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeRowCreateWithoutTournamentInput, Prisma.TimeRowUncheckedCreateWithoutTournamentInput>
}

export type TimeRowCreateManyTournamentInputEnvelope = {
  data: Prisma.TimeRowCreateManyTournamentInput | Prisma.TimeRowCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type TimeRowUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TimeRowWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeRowUpdateWithoutTournamentInput, Prisma.TimeRowUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TimeRowCreateWithoutTournamentInput, Prisma.TimeRowUncheckedCreateWithoutTournamentInput>
}

export type TimeRowUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TimeRowWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeRowUpdateWithoutTournamentInput, Prisma.TimeRowUncheckedUpdateWithoutTournamentInput>
}

export type TimeRowUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TimeRowScalarWhereInput
  data: Prisma.XOR<Prisma.TimeRowUpdateManyMutationInput, Prisma.TimeRowUncheckedUpdateManyWithoutTournamentInput>
}

export type TimeRowScalarWhereInput = {
  AND?: Prisma.TimeRowScalarWhereInput | Prisma.TimeRowScalarWhereInput[]
  OR?: Prisma.TimeRowScalarWhereInput[]
  NOT?: Prisma.TimeRowScalarWhereInput | Prisma.TimeRowScalarWhereInput[]
  id?: Prisma.StringFilter<"TimeRow"> | string
  tournamentId?: Prisma.StringNullableFilter<"TimeRow"> | string | null
  date?: Prisma.DateTimeFilter<"TimeRow"> | Date | string
  timeline?: Prisma.StringFilter<"TimeRow"> | string
  event?: Prisma.StringFilter<"TimeRow"> | string
}

export type TimeRowCreateManyTournamentInput = {
  id?: string
  date: Date | string
  timeline: string
  event: string
}

export type TimeRowUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TimeRowUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TimeRowUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  event?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TimeRowSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  date?: boolean
  timeline?: boolean
  event?: boolean
  tournament?: boolean | Prisma.TimeRow$tournamentArgs<ExtArgs>
}, ExtArgs["result"]["timeRow"]>

export type TimeRowSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  date?: boolean
  timeline?: boolean
  event?: boolean
  tournament?: boolean | Prisma.TimeRow$tournamentArgs<ExtArgs>
}, ExtArgs["result"]["timeRow"]>

export type TimeRowSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  date?: boolean
  timeline?: boolean
  event?: boolean
  tournament?: boolean | Prisma.TimeRow$tournamentArgs<ExtArgs>
}, ExtArgs["result"]["timeRow"]>

export type TimeRowSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  date?: boolean
  timeline?: boolean
  event?: boolean
}

export type TimeRowOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "date" | "timeline" | "event", ExtArgs["result"]["timeRow"]>
export type TimeRowInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TimeRow$tournamentArgs<ExtArgs>
}
export type TimeRowIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TimeRow$tournamentArgs<ExtArgs>
}
export type TimeRowIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TimeRow$tournamentArgs<ExtArgs>
}

export type $TimeRowPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TimeRow"
  objects: {
    tournament: Prisma.$TournamentPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tournamentId: string | null
    date: Date
    timeline: string
    event: string
  }, ExtArgs["result"]["timeRow"]>
  composites: {}
}

export type TimeRowGetPayload<S extends boolean | null | undefined | TimeRowDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TimeRowPayload, S>

export type TimeRowCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TimeRowFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TimeRowCountAggregateInputType | true
  }

export interface TimeRowDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TimeRow'], meta: { name: 'TimeRow' } }
  /**
   * Find zero or one TimeRow that matches the filter.
   * @param {TimeRowFindUniqueArgs} args - Arguments to find a TimeRow
   * @example
   * // Get one TimeRow
   * const timeRow = await prisma.timeRow.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TimeRowFindUniqueArgs>(args: Prisma.SelectSubset<T, TimeRowFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TimeRow that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TimeRowFindUniqueOrThrowArgs} args - Arguments to find a TimeRow
   * @example
   * // Get one TimeRow
   * const timeRow = await prisma.timeRow.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TimeRowFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TimeRowFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeRow that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowFindFirstArgs} args - Arguments to find a TimeRow
   * @example
   * // Get one TimeRow
   * const timeRow = await prisma.timeRow.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TimeRowFindFirstArgs>(args?: Prisma.SelectSubset<T, TimeRowFindFirstArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TimeRow that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowFindFirstOrThrowArgs} args - Arguments to find a TimeRow
   * @example
   * // Get one TimeRow
   * const timeRow = await prisma.timeRow.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TimeRowFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TimeRowFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TimeRows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TimeRows
   * const timeRows = await prisma.timeRow.findMany()
   * 
   * // Get first 10 TimeRows
   * const timeRows = await prisma.timeRow.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const timeRowWithIdOnly = await prisma.timeRow.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TimeRowFindManyArgs>(args?: Prisma.SelectSubset<T, TimeRowFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TimeRow.
   * @param {TimeRowCreateArgs} args - Arguments to create a TimeRow.
   * @example
   * // Create one TimeRow
   * const TimeRow = await prisma.timeRow.create({
   *   data: {
   *     // ... data to create a TimeRow
   *   }
   * })
   * 
   */
  create<T extends TimeRowCreateArgs>(args: Prisma.SelectSubset<T, TimeRowCreateArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TimeRows.
   * @param {TimeRowCreateManyArgs} args - Arguments to create many TimeRows.
   * @example
   * // Create many TimeRows
   * const timeRow = await prisma.timeRow.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TimeRowCreateManyArgs>(args?: Prisma.SelectSubset<T, TimeRowCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TimeRows and returns the data saved in the database.
   * @param {TimeRowCreateManyAndReturnArgs} args - Arguments to create many TimeRows.
   * @example
   * // Create many TimeRows
   * const timeRow = await prisma.timeRow.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TimeRows and only return the `id`
   * const timeRowWithIdOnly = await prisma.timeRow.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TimeRowCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TimeRowCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TimeRow.
   * @param {TimeRowDeleteArgs} args - Arguments to delete one TimeRow.
   * @example
   * // Delete one TimeRow
   * const TimeRow = await prisma.timeRow.delete({
   *   where: {
   *     // ... filter to delete one TimeRow
   *   }
   * })
   * 
   */
  delete<T extends TimeRowDeleteArgs>(args: Prisma.SelectSubset<T, TimeRowDeleteArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TimeRow.
   * @param {TimeRowUpdateArgs} args - Arguments to update one TimeRow.
   * @example
   * // Update one TimeRow
   * const timeRow = await prisma.timeRow.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TimeRowUpdateArgs>(args: Prisma.SelectSubset<T, TimeRowUpdateArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TimeRows.
   * @param {TimeRowDeleteManyArgs} args - Arguments to filter TimeRows to delete.
   * @example
   * // Delete a few TimeRows
   * const { count } = await prisma.timeRow.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TimeRowDeleteManyArgs>(args?: Prisma.SelectSubset<T, TimeRowDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeRows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TimeRows
   * const timeRow = await prisma.timeRow.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TimeRowUpdateManyArgs>(args: Prisma.SelectSubset<T, TimeRowUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TimeRows and returns the data updated in the database.
   * @param {TimeRowUpdateManyAndReturnArgs} args - Arguments to update many TimeRows.
   * @example
   * // Update many TimeRows
   * const timeRow = await prisma.timeRow.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TimeRows and only return the `id`
   * const timeRowWithIdOnly = await prisma.timeRow.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TimeRowUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TimeRowUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TimeRow.
   * @param {TimeRowUpsertArgs} args - Arguments to update or create a TimeRow.
   * @example
   * // Update or create a TimeRow
   * const timeRow = await prisma.timeRow.upsert({
   *   create: {
   *     // ... data to create a TimeRow
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TimeRow we want to update
   *   }
   * })
   */
  upsert<T extends TimeRowUpsertArgs>(args: Prisma.SelectSubset<T, TimeRowUpsertArgs<ExtArgs>>): Prisma.Prisma__TimeRowClient<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TimeRows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowCountArgs} args - Arguments to filter TimeRows to count.
   * @example
   * // Count the number of TimeRows
   * const count = await prisma.timeRow.count({
   *   where: {
   *     // ... the filter for the TimeRows we want to count
   *   }
   * })
  **/
  count<T extends TimeRowCountArgs>(
    args?: Prisma.Subset<T, TimeRowCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimeRowCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TimeRow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimeRowAggregateArgs>(args: Prisma.Subset<T, TimeRowAggregateArgs>): Prisma.PrismaPromise<GetTimeRowAggregateType<T>>

  /**
   * Group by TimeRow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeRowGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TimeRowGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TimeRowGroupByArgs['orderBy'] }
      : { orderBy?: TimeRowGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TimeRowGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimeRowGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TimeRow model
 */
readonly fields: TimeRowFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TimeRow.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TimeRowClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tournament<T extends Prisma.TimeRow$tournamentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TimeRow$tournamentArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TimeRow model
 */
export interface TimeRowFieldRefs {
  readonly id: Prisma.FieldRef<"TimeRow", 'String'>
  readonly tournamentId: Prisma.FieldRef<"TimeRow", 'String'>
  readonly date: Prisma.FieldRef<"TimeRow", 'DateTime'>
  readonly timeline: Prisma.FieldRef<"TimeRow", 'String'>
  readonly event: Prisma.FieldRef<"TimeRow", 'String'>
}
    

// Custom InputTypes
/**
 * TimeRow findUnique
 */
export type TimeRowFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * Filter, which TimeRow to fetch.
   */
  where: Prisma.TimeRowWhereUniqueInput
}

/**
 * TimeRow findUniqueOrThrow
 */
export type TimeRowFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * Filter, which TimeRow to fetch.
   */
  where: Prisma.TimeRowWhereUniqueInput
}

/**
 * TimeRow findFirst
 */
export type TimeRowFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * Filter, which TimeRow to fetch.
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeRows to fetch.
   */
  orderBy?: Prisma.TimeRowOrderByWithRelationInput | Prisma.TimeRowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeRows.
   */
  cursor?: Prisma.TimeRowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeRows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeRows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeRows.
   */
  distinct?: Prisma.TimeRowScalarFieldEnum | Prisma.TimeRowScalarFieldEnum[]
}

/**
 * TimeRow findFirstOrThrow
 */
export type TimeRowFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * Filter, which TimeRow to fetch.
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeRows to fetch.
   */
  orderBy?: Prisma.TimeRowOrderByWithRelationInput | Prisma.TimeRowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TimeRows.
   */
  cursor?: Prisma.TimeRowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeRows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeRows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeRows.
   */
  distinct?: Prisma.TimeRowScalarFieldEnum | Prisma.TimeRowScalarFieldEnum[]
}

/**
 * TimeRow findMany
 */
export type TimeRowFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * Filter, which TimeRows to fetch.
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TimeRows to fetch.
   */
  orderBy?: Prisma.TimeRowOrderByWithRelationInput | Prisma.TimeRowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TimeRows.
   */
  cursor?: Prisma.TimeRowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TimeRows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TimeRows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TimeRows.
   */
  distinct?: Prisma.TimeRowScalarFieldEnum | Prisma.TimeRowScalarFieldEnum[]
}

/**
 * TimeRow create
 */
export type TimeRowCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * The data needed to create a TimeRow.
   */
  data: Prisma.XOR<Prisma.TimeRowCreateInput, Prisma.TimeRowUncheckedCreateInput>
}

/**
 * TimeRow createMany
 */
export type TimeRowCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TimeRows.
   */
  data: Prisma.TimeRowCreateManyInput | Prisma.TimeRowCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TimeRow createManyAndReturn
 */
export type TimeRowCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * The data used to create many TimeRows.
   */
  data: Prisma.TimeRowCreateManyInput | Prisma.TimeRowCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TimeRow update
 */
export type TimeRowUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * The data needed to update a TimeRow.
   */
  data: Prisma.XOR<Prisma.TimeRowUpdateInput, Prisma.TimeRowUncheckedUpdateInput>
  /**
   * Choose, which TimeRow to update.
   */
  where: Prisma.TimeRowWhereUniqueInput
}

/**
 * TimeRow updateMany
 */
export type TimeRowUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TimeRows.
   */
  data: Prisma.XOR<Prisma.TimeRowUpdateManyMutationInput, Prisma.TimeRowUncheckedUpdateManyInput>
  /**
   * Filter which TimeRows to update
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * Limit how many TimeRows to update.
   */
  limit?: number
}

/**
 * TimeRow updateManyAndReturn
 */
export type TimeRowUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * The data used to update TimeRows.
   */
  data: Prisma.XOR<Prisma.TimeRowUpdateManyMutationInput, Prisma.TimeRowUncheckedUpdateManyInput>
  /**
   * Filter which TimeRows to update
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * Limit how many TimeRows to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TimeRow upsert
 */
export type TimeRowUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * The filter to search for the TimeRow to update in case it exists.
   */
  where: Prisma.TimeRowWhereUniqueInput
  /**
   * In case the TimeRow found by the `where` argument doesn't exist, create a new TimeRow with this data.
   */
  create: Prisma.XOR<Prisma.TimeRowCreateInput, Prisma.TimeRowUncheckedCreateInput>
  /**
   * In case the TimeRow was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TimeRowUpdateInput, Prisma.TimeRowUncheckedUpdateInput>
}

/**
 * TimeRow delete
 */
export type TimeRowDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  /**
   * Filter which TimeRow to delete.
   */
  where: Prisma.TimeRowWhereUniqueInput
}

/**
 * TimeRow deleteMany
 */
export type TimeRowDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TimeRows to delete
   */
  where?: Prisma.TimeRowWhereInput
  /**
   * Limit how many TimeRows to delete.
   */
  limit?: number
}

/**
 * TimeRow.tournament
 */
export type TimeRow$tournamentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  where?: Prisma.TournamentWhereInput
}

/**
 * TimeRow without action
 */
export type TimeRowDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
}
