
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tournament` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Tournament
 * 
 */
export type TournamentModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentPayload>

export type AggregateTournament = {
  _count: TournamentCountAggregateOutputType | null
  _min: TournamentMinAggregateOutputType | null
  _max: TournamentMaxAggregateOutputType | null
}

export type TournamentMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  info: string | null
  place: string | null
  startDate: Date | null
  endDate: Date | null
}

export type TournamentMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  info: string | null
  place: string | null
  startDate: Date | null
  endDate: Date | null
}

export type TournamentCountAggregateOutputType = {
  id: number
  name: number
  description: number
  info: number
  place: number
  startDate: number
  endDate: number
  _all: number
}


export type TournamentMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  info?: true
  place?: true
  startDate?: true
  endDate?: true
}

export type TournamentMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  info?: true
  place?: true
  startDate?: true
  endDate?: true
}

export type TournamentCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  info?: true
  place?: true
  startDate?: true
  endDate?: true
  _all?: true
}

export type TournamentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tournament to aggregate.
   */
  where?: Prisma.TournamentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tournaments to fetch.
   */
  orderBy?: Prisma.TournamentOrderByWithRelationInput | Prisma.TournamentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tournaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tournaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tournaments
  **/
  _count?: true | TournamentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentMaxAggregateInputType
}

export type GetTournamentAggregateType<T extends TournamentAggregateArgs> = {
      [P in keyof T & keyof AggregateTournament]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournament[P]>
    : Prisma.GetScalarType<T[P], AggregateTournament[P]>
}




export type TournamentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentWhereInput
  orderBy?: Prisma.TournamentOrderByWithAggregationInput | Prisma.TournamentOrderByWithAggregationInput[]
  by: Prisma.TournamentScalarFieldEnum[] | Prisma.TournamentScalarFieldEnum
  having?: Prisma.TournamentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentCountAggregateInputType | true
  _min?: TournamentMinAggregateInputType
  _max?: TournamentMaxAggregateInputType
}

export type TournamentGroupByOutputType = {
  id: string
  name: string
  description: string | null
  info: string
  place: string
  startDate: Date
  endDate: Date | null
  _count: TournamentCountAggregateOutputType | null
  _min: TournamentMinAggregateOutputType | null
  _max: TournamentMaxAggregateOutputType | null
}

export type GetTournamentGroupByPayload<T extends TournamentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentGroupByOutputType[P]>
      }
    >
  >



export type TournamentWhereInput = {
  AND?: Prisma.TournamentWhereInput | Prisma.TournamentWhereInput[]
  OR?: Prisma.TournamentWhereInput[]
  NOT?: Prisma.TournamentWhereInput | Prisma.TournamentWhereInput[]
  id?: Prisma.StringFilter<"Tournament"> | string
  name?: Prisma.StringFilter<"Tournament"> | string
  description?: Prisma.StringNullableFilter<"Tournament"> | string | null
  info?: Prisma.StringFilter<"Tournament"> | string
  place?: Prisma.StringFilter<"Tournament"> | string
  startDate?: Prisma.DateTimeFilter<"Tournament"> | Date | string
  endDate?: Prisma.DateTimeNullableFilter<"Tournament"> | Date | string | null
  categories?: Prisma.CategoryListRelationFilter
  timetable?: Prisma.TimeRowListRelationFilter
  fighters?: Prisma.FighterListRelationFilter
  matches?: Prisma.MatchListRelationFilter
  clubs?: Prisma.ClubListRelationFilter
}

export type TournamentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  info?: Prisma.SortOrder
  place?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  categories?: Prisma.CategoryOrderByRelationAggregateInput
  timetable?: Prisma.TimeRowOrderByRelationAggregateInput
  fighters?: Prisma.FighterOrderByRelationAggregateInput
  matches?: Prisma.MatchOrderByRelationAggregateInput
  clubs?: Prisma.ClubOrderByRelationAggregateInput
}

export type TournamentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TournamentWhereInput | Prisma.TournamentWhereInput[]
  OR?: Prisma.TournamentWhereInput[]
  NOT?: Prisma.TournamentWhereInput | Prisma.TournamentWhereInput[]
  name?: Prisma.StringFilter<"Tournament"> | string
  description?: Prisma.StringNullableFilter<"Tournament"> | string | null
  info?: Prisma.StringFilter<"Tournament"> | string
  place?: Prisma.StringFilter<"Tournament"> | string
  startDate?: Prisma.DateTimeFilter<"Tournament"> | Date | string
  endDate?: Prisma.DateTimeNullableFilter<"Tournament"> | Date | string | null
  categories?: Prisma.CategoryListRelationFilter
  timetable?: Prisma.TimeRowListRelationFilter
  fighters?: Prisma.FighterListRelationFilter
  matches?: Prisma.MatchListRelationFilter
  clubs?: Prisma.ClubListRelationFilter
}, "id">

export type TournamentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  info?: Prisma.SortOrder
  place?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TournamentCountOrderByAggregateInput
  _max?: Prisma.TournamentMaxOrderByAggregateInput
  _min?: Prisma.TournamentMinOrderByAggregateInput
}

export type TournamentScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentScalarWhereWithAggregatesInput | Prisma.TournamentScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentScalarWhereWithAggregatesInput | Prisma.TournamentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Tournament"> | string
  name?: Prisma.StringWithAggregatesFilter<"Tournament"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Tournament"> | string | null
  info?: Prisma.StringWithAggregatesFilter<"Tournament"> | string
  place?: Prisma.StringWithAggregatesFilter<"Tournament"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"Tournament"> | Date | string
  endDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Tournament"> | Date | string | null
}

export type TournamentCreateInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubCreateNestedManyWithoutTournamentInput
}

export type TournamentUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowUncheckedCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubUncheckedCreateNestedManyWithoutTournamentInput
}

export type TournamentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUpdateManyWithoutTournamentNestedInput
}

export type TournamentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUncheckedUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUncheckedUpdateManyWithoutTournamentNestedInput
}

export type TournamentCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
}

export type TournamentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TournamentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TournamentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  info?: Prisma.SortOrder
  place?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
}

export type TournamentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  info?: Prisma.SortOrder
  place?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
}

export type TournamentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  info?: Prisma.SortOrder
  place?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
}

export type TournamentNullableScalarRelationFilter = {
  is?: Prisma.TournamentWhereInput | null
  isNot?: Prisma.TournamentWhereInput | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type TournamentCreateNestedOneWithoutClubsInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutClubsInput, Prisma.TournamentUncheckedCreateWithoutClubsInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutClubsInput
  connect?: Prisma.TournamentWhereUniqueInput
}

export type TournamentUpdateOneWithoutClubsNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutClubsInput, Prisma.TournamentUncheckedCreateWithoutClubsInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutClubsInput
  upsert?: Prisma.TournamentUpsertWithoutClubsInput
  disconnect?: Prisma.TournamentWhereInput | boolean
  delete?: Prisma.TournamentWhereInput | boolean
  connect?: Prisma.TournamentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TournamentUpdateToOneWithWhereWithoutClubsInput, Prisma.TournamentUpdateWithoutClubsInput>, Prisma.TournamentUncheckedUpdateWithoutClubsInput>
}

export type TournamentCreateNestedOneWithoutTimetableInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutTimetableInput, Prisma.TournamentUncheckedCreateWithoutTimetableInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutTimetableInput
  connect?: Prisma.TournamentWhereUniqueInput
}

export type TournamentUpdateOneWithoutTimetableNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutTimetableInput, Prisma.TournamentUncheckedCreateWithoutTimetableInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutTimetableInput
  upsert?: Prisma.TournamentUpsertWithoutTimetableInput
  disconnect?: Prisma.TournamentWhereInput | boolean
  delete?: Prisma.TournamentWhereInput | boolean
  connect?: Prisma.TournamentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TournamentUpdateToOneWithWhereWithoutTimetableInput, Prisma.TournamentUpdateWithoutTimetableInput>, Prisma.TournamentUncheckedUpdateWithoutTimetableInput>
}

export type TournamentCreateNestedOneWithoutCategoriesInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutCategoriesInput, Prisma.TournamentUncheckedCreateWithoutCategoriesInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutCategoriesInput
  connect?: Prisma.TournamentWhereUniqueInput
}

export type TournamentUpdateOneWithoutCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutCategoriesInput, Prisma.TournamentUncheckedCreateWithoutCategoriesInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutCategoriesInput
  upsert?: Prisma.TournamentUpsertWithoutCategoriesInput
  disconnect?: Prisma.TournamentWhereInput | boolean
  delete?: Prisma.TournamentWhereInput | boolean
  connect?: Prisma.TournamentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TournamentUpdateToOneWithWhereWithoutCategoriesInput, Prisma.TournamentUpdateWithoutCategoriesInput>, Prisma.TournamentUncheckedUpdateWithoutCategoriesInput>
}

export type TournamentCreateNestedOneWithoutMatchesInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutMatchesInput, Prisma.TournamentUncheckedCreateWithoutMatchesInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutMatchesInput
  connect?: Prisma.TournamentWhereUniqueInput
}

export type TournamentUpdateOneWithoutMatchesNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutMatchesInput, Prisma.TournamentUncheckedCreateWithoutMatchesInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutMatchesInput
  upsert?: Prisma.TournamentUpsertWithoutMatchesInput
  disconnect?: Prisma.TournamentWhereInput | boolean
  delete?: Prisma.TournamentWhereInput | boolean
  connect?: Prisma.TournamentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TournamentUpdateToOneWithWhereWithoutMatchesInput, Prisma.TournamentUpdateWithoutMatchesInput>, Prisma.TournamentUncheckedUpdateWithoutMatchesInput>
}

export type TournamentCreateNestedOneWithoutFightersInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutFightersInput, Prisma.TournamentUncheckedCreateWithoutFightersInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutFightersInput
  connect?: Prisma.TournamentWhereUniqueInput
}

export type TournamentUpdateOneWithoutFightersNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentCreateWithoutFightersInput, Prisma.TournamentUncheckedCreateWithoutFightersInput>
  connectOrCreate?: Prisma.TournamentCreateOrConnectWithoutFightersInput
  upsert?: Prisma.TournamentUpsertWithoutFightersInput
  disconnect?: Prisma.TournamentWhereInput | boolean
  delete?: Prisma.TournamentWhereInput | boolean
  connect?: Prisma.TournamentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TournamentUpdateToOneWithWhereWithoutFightersInput, Prisma.TournamentUpdateWithoutFightersInput>, Prisma.TournamentUncheckedUpdateWithoutFightersInput>
}

export type TournamentCreateWithoutClubsInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchCreateNestedManyWithoutTournamentInput
}

export type TournamentUncheckedCreateWithoutClubsInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowUncheckedCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutTournamentInput
}

export type TournamentCreateOrConnectWithoutClubsInput = {
  where: Prisma.TournamentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentCreateWithoutClubsInput, Prisma.TournamentUncheckedCreateWithoutClubsInput>
}

export type TournamentUpsertWithoutClubsInput = {
  update: Prisma.XOR<Prisma.TournamentUpdateWithoutClubsInput, Prisma.TournamentUncheckedUpdateWithoutClubsInput>
  create: Prisma.XOR<Prisma.TournamentCreateWithoutClubsInput, Prisma.TournamentUncheckedCreateWithoutClubsInput>
  where?: Prisma.TournamentWhereInput
}

export type TournamentUpdateToOneWithWhereWithoutClubsInput = {
  where?: Prisma.TournamentWhereInput
  data: Prisma.XOR<Prisma.TournamentUpdateWithoutClubsInput, Prisma.TournamentUncheckedUpdateWithoutClubsInput>
}

export type TournamentUpdateWithoutClubsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUpdateManyWithoutTournamentNestedInput
}

export type TournamentUncheckedUpdateWithoutClubsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUncheckedUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutTournamentNestedInput
}

export type TournamentCreateWithoutTimetableInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubCreateNestedManyWithoutTournamentInput
}

export type TournamentUncheckedCreateWithoutTimetableInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubUncheckedCreateNestedManyWithoutTournamentInput
}

export type TournamentCreateOrConnectWithoutTimetableInput = {
  where: Prisma.TournamentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentCreateWithoutTimetableInput, Prisma.TournamentUncheckedCreateWithoutTimetableInput>
}

export type TournamentUpsertWithoutTimetableInput = {
  update: Prisma.XOR<Prisma.TournamentUpdateWithoutTimetableInput, Prisma.TournamentUncheckedUpdateWithoutTimetableInput>
  create: Prisma.XOR<Prisma.TournamentCreateWithoutTimetableInput, Prisma.TournamentUncheckedCreateWithoutTimetableInput>
  where?: Prisma.TournamentWhereInput
}

export type TournamentUpdateToOneWithWhereWithoutTimetableInput = {
  where?: Prisma.TournamentWhereInput
  data: Prisma.XOR<Prisma.TournamentUpdateWithoutTimetableInput, Prisma.TournamentUncheckedUpdateWithoutTimetableInput>
}

export type TournamentUpdateWithoutTimetableInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUpdateManyWithoutTournamentNestedInput
}

export type TournamentUncheckedUpdateWithoutTimetableInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUncheckedUpdateManyWithoutTournamentNestedInput
}

export type TournamentCreateWithoutCategoriesInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  timetable?: Prisma.TimeRowCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubCreateNestedManyWithoutTournamentInput
}

export type TournamentUncheckedCreateWithoutCategoriesInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  timetable?: Prisma.TimeRowUncheckedCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubUncheckedCreateNestedManyWithoutTournamentInput
}

export type TournamentCreateOrConnectWithoutCategoriesInput = {
  where: Prisma.TournamentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentCreateWithoutCategoriesInput, Prisma.TournamentUncheckedCreateWithoutCategoriesInput>
}

export type TournamentUpsertWithoutCategoriesInput = {
  update: Prisma.XOR<Prisma.TournamentUpdateWithoutCategoriesInput, Prisma.TournamentUncheckedUpdateWithoutCategoriesInput>
  create: Prisma.XOR<Prisma.TournamentCreateWithoutCategoriesInput, Prisma.TournamentUncheckedCreateWithoutCategoriesInput>
  where?: Prisma.TournamentWhereInput
}

export type TournamentUpdateToOneWithWhereWithoutCategoriesInput = {
  where?: Prisma.TournamentWhereInput
  data: Prisma.XOR<Prisma.TournamentUpdateWithoutCategoriesInput, Prisma.TournamentUncheckedUpdateWithoutCategoriesInput>
}

export type TournamentUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  timetable?: Prisma.TimeRowUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUpdateManyWithoutTournamentNestedInput
}

export type TournamentUncheckedUpdateWithoutCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  timetable?: Prisma.TimeRowUncheckedUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUncheckedUpdateManyWithoutTournamentNestedInput
}

export type TournamentCreateWithoutMatchesInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubCreateNestedManyWithoutTournamentInput
}

export type TournamentUncheckedCreateWithoutMatchesInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowUncheckedCreateNestedManyWithoutTournamentInput
  fighters?: Prisma.FighterUncheckedCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubUncheckedCreateNestedManyWithoutTournamentInput
}

export type TournamentCreateOrConnectWithoutMatchesInput = {
  where: Prisma.TournamentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentCreateWithoutMatchesInput, Prisma.TournamentUncheckedCreateWithoutMatchesInput>
}

export type TournamentUpsertWithoutMatchesInput = {
  update: Prisma.XOR<Prisma.TournamentUpdateWithoutMatchesInput, Prisma.TournamentUncheckedUpdateWithoutMatchesInput>
  create: Prisma.XOR<Prisma.TournamentCreateWithoutMatchesInput, Prisma.TournamentUncheckedCreateWithoutMatchesInput>
  where?: Prisma.TournamentWhereInput
}

export type TournamentUpdateToOneWithWhereWithoutMatchesInput = {
  where?: Prisma.TournamentWhereInput
  data: Prisma.XOR<Prisma.TournamentUpdateWithoutMatchesInput, Prisma.TournamentUncheckedUpdateWithoutMatchesInput>
}

export type TournamentUpdateWithoutMatchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUpdateManyWithoutTournamentNestedInput
}

export type TournamentUncheckedUpdateWithoutMatchesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUncheckedUpdateManyWithoutTournamentNestedInput
  fighters?: Prisma.FighterUncheckedUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUncheckedUpdateManyWithoutTournamentNestedInput
}

export type TournamentCreateWithoutFightersInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubCreateNestedManyWithoutTournamentInput
}

export type TournamentUncheckedCreateWithoutFightersInput = {
  id?: string
  name: string
  description?: string | null
  info: string
  place: string
  startDate: Date | string
  endDate?: Date | string | null
  categories?: Prisma.CategoryUncheckedCreateNestedManyWithoutTournamentInput
  timetable?: Prisma.TimeRowUncheckedCreateNestedManyWithoutTournamentInput
  matches?: Prisma.MatchUncheckedCreateNestedManyWithoutTournamentInput
  clubs?: Prisma.ClubUncheckedCreateNestedManyWithoutTournamentInput
}

export type TournamentCreateOrConnectWithoutFightersInput = {
  where: Prisma.TournamentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentCreateWithoutFightersInput, Prisma.TournamentUncheckedCreateWithoutFightersInput>
}

export type TournamentUpsertWithoutFightersInput = {
  update: Prisma.XOR<Prisma.TournamentUpdateWithoutFightersInput, Prisma.TournamentUncheckedUpdateWithoutFightersInput>
  create: Prisma.XOR<Prisma.TournamentCreateWithoutFightersInput, Prisma.TournamentUncheckedCreateWithoutFightersInput>
  where?: Prisma.TournamentWhereInput
}

export type TournamentUpdateToOneWithWhereWithoutFightersInput = {
  where?: Prisma.TournamentWhereInput
  data: Prisma.XOR<Prisma.TournamentUpdateWithoutFightersInput, Prisma.TournamentUncheckedUpdateWithoutFightersInput>
}

export type TournamentUpdateWithoutFightersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUpdateManyWithoutTournamentNestedInput
}

export type TournamentUncheckedUpdateWithoutFightersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  info?: Prisma.StringFieldUpdateOperationsInput | string
  place?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  categories?: Prisma.CategoryUncheckedUpdateManyWithoutTournamentNestedInput
  timetable?: Prisma.TimeRowUncheckedUpdateManyWithoutTournamentNestedInput
  matches?: Prisma.MatchUncheckedUpdateManyWithoutTournamentNestedInput
  clubs?: Prisma.ClubUncheckedUpdateManyWithoutTournamentNestedInput
}


/**
 * Count Type TournamentCountOutputType
 */

export type TournamentCountOutputType = {
  categories: number
  timetable: number
  fighters: number
  matches: number
  clubs: number
}

export type TournamentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  categories?: boolean | TournamentCountOutputTypeCountCategoriesArgs
  timetable?: boolean | TournamentCountOutputTypeCountTimetableArgs
  fighters?: boolean | TournamentCountOutputTypeCountFightersArgs
  matches?: boolean | TournamentCountOutputTypeCountMatchesArgs
  clubs?: boolean | TournamentCountOutputTypeCountClubsArgs
}

/**
 * TournamentCountOutputType without action
 */
export type TournamentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentCountOutputType
   */
  select?: Prisma.TournamentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TournamentCountOutputType without action
 */
export type TournamentCountOutputTypeCountCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CategoryWhereInput
}

/**
 * TournamentCountOutputType without action
 */
export type TournamentCountOutputTypeCountTimetableArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeRowWhereInput
}

/**
 * TournamentCountOutputType without action
 */
export type TournamentCountOutputTypeCountFightersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FighterWhereInput
}

/**
 * TournamentCountOutputType without action
 */
export type TournamentCountOutputTypeCountMatchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchWhereInput
}

/**
 * TournamentCountOutputType without action
 */
export type TournamentCountOutputTypeCountClubsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClubWhereInput
}


export type TournamentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  info?: boolean
  place?: boolean
  startDate?: boolean
  endDate?: boolean
  categories?: boolean | Prisma.Tournament$categoriesArgs<ExtArgs>
  timetable?: boolean | Prisma.Tournament$timetableArgs<ExtArgs>
  fighters?: boolean | Prisma.Tournament$fightersArgs<ExtArgs>
  matches?: boolean | Prisma.Tournament$matchesArgs<ExtArgs>
  clubs?: boolean | Prisma.Tournament$clubsArgs<ExtArgs>
  _count?: boolean | Prisma.TournamentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournament"]>

export type TournamentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  info?: boolean
  place?: boolean
  startDate?: boolean
  endDate?: boolean
}, ExtArgs["result"]["tournament"]>

export type TournamentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  info?: boolean
  place?: boolean
  startDate?: boolean
  endDate?: boolean
}, ExtArgs["result"]["tournament"]>

export type TournamentSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  info?: boolean
  place?: boolean
  startDate?: boolean
  endDate?: boolean
}

export type TournamentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "info" | "place" | "startDate" | "endDate", ExtArgs["result"]["tournament"]>
export type TournamentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  categories?: boolean | Prisma.Tournament$categoriesArgs<ExtArgs>
  timetable?: boolean | Prisma.Tournament$timetableArgs<ExtArgs>
  fighters?: boolean | Prisma.Tournament$fightersArgs<ExtArgs>
  matches?: boolean | Prisma.Tournament$matchesArgs<ExtArgs>
  clubs?: boolean | Prisma.Tournament$clubsArgs<ExtArgs>
  _count?: boolean | Prisma.TournamentCountOutputTypeDefaultArgs<ExtArgs>
}
export type TournamentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TournamentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TournamentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tournament"
  objects: {
    categories: Prisma.$CategoryPayload<ExtArgs>[]
    timetable: Prisma.$TimeRowPayload<ExtArgs>[]
    fighters: Prisma.$FighterPayload<ExtArgs>[]
    matches: Prisma.$MatchPayload<ExtArgs>[]
    clubs: Prisma.$ClubPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    info: string
    place: string
    startDate: Date
    endDate: Date | null
  }, ExtArgs["result"]["tournament"]>
  composites: {}
}

export type TournamentGetPayload<S extends boolean | null | undefined | TournamentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentPayload, S>

export type TournamentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentCountAggregateInputType | true
  }

export interface TournamentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tournament'], meta: { name: 'Tournament' } }
  /**
   * Find zero or one Tournament that matches the filter.
   * @param {TournamentFindUniqueArgs} args - Arguments to find a Tournament
   * @example
   * // Get one Tournament
   * const tournament = await prisma.tournament.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tournament that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentFindUniqueOrThrowArgs} args - Arguments to find a Tournament
   * @example
   * // Get one Tournament
   * const tournament = await prisma.tournament.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tournament that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentFindFirstArgs} args - Arguments to find a Tournament
   * @example
   * // Get one Tournament
   * const tournament = await prisma.tournament.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tournament that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentFindFirstOrThrowArgs} args - Arguments to find a Tournament
   * @example
   * // Get one Tournament
   * const tournament = await prisma.tournament.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tournaments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tournaments
   * const tournaments = await prisma.tournament.findMany()
   * 
   * // Get first 10 Tournaments
   * const tournaments = await prisma.tournament.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentWithIdOnly = await prisma.tournament.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tournament.
   * @param {TournamentCreateArgs} args - Arguments to create a Tournament.
   * @example
   * // Create one Tournament
   * const Tournament = await prisma.tournament.create({
   *   data: {
   *     // ... data to create a Tournament
   *   }
   * })
   * 
   */
  create<T extends TournamentCreateArgs>(args: Prisma.SelectSubset<T, TournamentCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tournaments.
   * @param {TournamentCreateManyArgs} args - Arguments to create many Tournaments.
   * @example
   * // Create many Tournaments
   * const tournament = await prisma.tournament.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tournaments and returns the data saved in the database.
   * @param {TournamentCreateManyAndReturnArgs} args - Arguments to create many Tournaments.
   * @example
   * // Create many Tournaments
   * const tournament = await prisma.tournament.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tournaments and only return the `id`
   * const tournamentWithIdOnly = await prisma.tournament.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tournament.
   * @param {TournamentDeleteArgs} args - Arguments to delete one Tournament.
   * @example
   * // Delete one Tournament
   * const Tournament = await prisma.tournament.delete({
   *   where: {
   *     // ... filter to delete one Tournament
   *   }
   * })
   * 
   */
  delete<T extends TournamentDeleteArgs>(args: Prisma.SelectSubset<T, TournamentDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tournament.
   * @param {TournamentUpdateArgs} args - Arguments to update one Tournament.
   * @example
   * // Update one Tournament
   * const tournament = await prisma.tournament.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentUpdateArgs>(args: Prisma.SelectSubset<T, TournamentUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tournaments.
   * @param {TournamentDeleteManyArgs} args - Arguments to filter Tournaments to delete.
   * @example
   * // Delete a few Tournaments
   * const { count } = await prisma.tournament.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tournaments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tournaments
   * const tournament = await prisma.tournament.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tournaments and returns the data updated in the database.
   * @param {TournamentUpdateManyAndReturnArgs} args - Arguments to update many Tournaments.
   * @example
   * // Update many Tournaments
   * const tournament = await prisma.tournament.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tournaments and only return the `id`
   * const tournamentWithIdOnly = await prisma.tournament.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tournament.
   * @param {TournamentUpsertArgs} args - Arguments to update or create a Tournament.
   * @example
   * // Update or create a Tournament
   * const tournament = await prisma.tournament.upsert({
   *   create: {
   *     // ... data to create a Tournament
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tournament we want to update
   *   }
   * })
   */
  upsert<T extends TournamentUpsertArgs>(args: Prisma.SelectSubset<T, TournamentUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tournaments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentCountArgs} args - Arguments to filter Tournaments to count.
   * @example
   * // Count the number of Tournaments
   * const count = await prisma.tournament.count({
   *   where: {
   *     // ... the filter for the Tournaments we want to count
   *   }
   * })
  **/
  count<T extends TournamentCountArgs>(
    args?: Prisma.Subset<T, TournamentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tournament.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentAggregateArgs>(args: Prisma.Subset<T, TournamentAggregateArgs>): Prisma.PrismaPromise<GetTournamentAggregateType<T>>

  /**
   * Group by Tournament.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentGroupByArgs['orderBy'] }
      : { orderBy?: TournamentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tournament model
 */
readonly fields: TournamentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tournament.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  categories<T extends Prisma.Tournament$categoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tournament$categoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  timetable<T extends Prisma.Tournament$timetableArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tournament$timetableArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimeRowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  fighters<T extends Prisma.Tournament$fightersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tournament$fightersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FighterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  matches<T extends Prisma.Tournament$matchesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tournament$matchesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  clubs<T extends Prisma.Tournament$clubsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tournament$clubsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tournament model
 */
export interface TournamentFieldRefs {
  readonly id: Prisma.FieldRef<"Tournament", 'String'>
  readonly name: Prisma.FieldRef<"Tournament", 'String'>
  readonly description: Prisma.FieldRef<"Tournament", 'String'>
  readonly info: Prisma.FieldRef<"Tournament", 'String'>
  readonly place: Prisma.FieldRef<"Tournament", 'String'>
  readonly startDate: Prisma.FieldRef<"Tournament", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"Tournament", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Tournament findUnique
 */
export type TournamentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * Filter, which Tournament to fetch.
   */
  where: Prisma.TournamentWhereUniqueInput
}

/**
 * Tournament findUniqueOrThrow
 */
export type TournamentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * Filter, which Tournament to fetch.
   */
  where: Prisma.TournamentWhereUniqueInput
}

/**
 * Tournament findFirst
 */
export type TournamentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * Filter, which Tournament to fetch.
   */
  where?: Prisma.TournamentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tournaments to fetch.
   */
  orderBy?: Prisma.TournamentOrderByWithRelationInput | Prisma.TournamentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tournaments.
   */
  cursor?: Prisma.TournamentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tournaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tournaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tournaments.
   */
  distinct?: Prisma.TournamentScalarFieldEnum | Prisma.TournamentScalarFieldEnum[]
}

/**
 * Tournament findFirstOrThrow
 */
export type TournamentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * Filter, which Tournament to fetch.
   */
  where?: Prisma.TournamentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tournaments to fetch.
   */
  orderBy?: Prisma.TournamentOrderByWithRelationInput | Prisma.TournamentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tournaments.
   */
  cursor?: Prisma.TournamentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tournaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tournaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tournaments.
   */
  distinct?: Prisma.TournamentScalarFieldEnum | Prisma.TournamentScalarFieldEnum[]
}

/**
 * Tournament findMany
 */
export type TournamentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * Filter, which Tournaments to fetch.
   */
  where?: Prisma.TournamentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tournaments to fetch.
   */
  orderBy?: Prisma.TournamentOrderByWithRelationInput | Prisma.TournamentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tournaments.
   */
  cursor?: Prisma.TournamentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tournaments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tournaments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tournaments.
   */
  distinct?: Prisma.TournamentScalarFieldEnum | Prisma.TournamentScalarFieldEnum[]
}

/**
 * Tournament create
 */
export type TournamentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * The data needed to create a Tournament.
   */
  data: Prisma.XOR<Prisma.TournamentCreateInput, Prisma.TournamentUncheckedCreateInput>
}

/**
 * Tournament createMany
 */
export type TournamentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tournaments.
   */
  data: Prisma.TournamentCreateManyInput | Prisma.TournamentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tournament createManyAndReturn
 */
export type TournamentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * The data used to create many Tournaments.
   */
  data: Prisma.TournamentCreateManyInput | Prisma.TournamentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tournament update
 */
export type TournamentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * The data needed to update a Tournament.
   */
  data: Prisma.XOR<Prisma.TournamentUpdateInput, Prisma.TournamentUncheckedUpdateInput>
  /**
   * Choose, which Tournament to update.
   */
  where: Prisma.TournamentWhereUniqueInput
}

/**
 * Tournament updateMany
 */
export type TournamentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tournaments.
   */
  data: Prisma.XOR<Prisma.TournamentUpdateManyMutationInput, Prisma.TournamentUncheckedUpdateManyInput>
  /**
   * Filter which Tournaments to update
   */
  where?: Prisma.TournamentWhereInput
  /**
   * Limit how many Tournaments to update.
   */
  limit?: number
}

/**
 * Tournament updateManyAndReturn
 */
export type TournamentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * The data used to update Tournaments.
   */
  data: Prisma.XOR<Prisma.TournamentUpdateManyMutationInput, Prisma.TournamentUncheckedUpdateManyInput>
  /**
   * Filter which Tournaments to update
   */
  where?: Prisma.TournamentWhereInput
  /**
   * Limit how many Tournaments to update.
   */
  limit?: number
}

/**
 * Tournament upsert
 */
export type TournamentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * The filter to search for the Tournament to update in case it exists.
   */
  where: Prisma.TournamentWhereUniqueInput
  /**
   * In case the Tournament found by the `where` argument doesn't exist, create a new Tournament with this data.
   */
  create: Prisma.XOR<Prisma.TournamentCreateInput, Prisma.TournamentUncheckedCreateInput>
  /**
   * In case the Tournament was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentUpdateInput, Prisma.TournamentUncheckedUpdateInput>
}

/**
 * Tournament delete
 */
export type TournamentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
  /**
   * Filter which Tournament to delete.
   */
  where: Prisma.TournamentWhereUniqueInput
}

/**
 * Tournament deleteMany
 */
export type TournamentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tournaments to delete
   */
  where?: Prisma.TournamentWhereInput
  /**
   * Limit how many Tournaments to delete.
   */
  limit?: number
}

/**
 * Tournament.categories
 */
export type Tournament$categoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Category
   */
  select?: Prisma.CategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Category
   */
  omit?: Prisma.CategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CategoryInclude<ExtArgs> | null
  where?: Prisma.CategoryWhereInput
  orderBy?: Prisma.CategoryOrderByWithRelationInput | Prisma.CategoryOrderByWithRelationInput[]
  cursor?: Prisma.CategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CategoryScalarFieldEnum | Prisma.CategoryScalarFieldEnum[]
}

/**
 * Tournament.timetable
 */
export type Tournament$timetableArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeRow
   */
  select?: Prisma.TimeRowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TimeRow
   */
  omit?: Prisma.TimeRowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeRowInclude<ExtArgs> | null
  where?: Prisma.TimeRowWhereInput
  orderBy?: Prisma.TimeRowOrderByWithRelationInput | Prisma.TimeRowOrderByWithRelationInput[]
  cursor?: Prisma.TimeRowWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TimeRowScalarFieldEnum | Prisma.TimeRowScalarFieldEnum[]
}

/**
 * Tournament.fighters
 */
export type Tournament$fightersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fighter
   */
  select?: Prisma.FighterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fighter
   */
  omit?: Prisma.FighterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FighterInclude<ExtArgs> | null
  where?: Prisma.FighterWhereInput
  orderBy?: Prisma.FighterOrderByWithRelationInput | Prisma.FighterOrderByWithRelationInput[]
  cursor?: Prisma.FighterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FighterScalarFieldEnum | Prisma.FighterScalarFieldEnum[]
}

/**
 * Tournament.matches
 */
export type Tournament$matchesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  where?: Prisma.MatchWhereInput
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  cursor?: Prisma.MatchWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Tournament.clubs
 */
export type Tournament$clubsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Club
   */
  select?: Prisma.ClubSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Club
   */
  omit?: Prisma.ClubOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubInclude<ExtArgs> | null
  where?: Prisma.ClubWhereInput
  orderBy?: Prisma.ClubOrderByWithRelationInput | Prisma.ClubOrderByWithRelationInput[]
  cursor?: Prisma.ClubWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ClubScalarFieldEnum | Prisma.ClubScalarFieldEnum[]
}

/**
 * Tournament without action
 */
export type TournamentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tournament
   */
  select?: Prisma.TournamentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tournament
   */
  omit?: Prisma.TournamentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentInclude<ExtArgs> | null
}
